# Generated by Django 6.0.6 on 2026-06-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrichTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, help_text='Geohash-8 of (lat, lng) — matches PubHours.cache_key.', max_length=12, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('city', models.CharField(blank=True, help_text='Optional city hint passed by the mobile app.', max_length=128, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('done', models.BooleanField(db_index=True, default=False, help_text='True once the task has been processed successfully (or max_attempts exceeded).')),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Enrich Task',
                'verbose_name_plural': 'Enrich Tasks',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PubHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, help_text='Geohash-8 of (lat, lng) — ~38 m precision.', max_length=12, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('opening_hours_raw', models.CharField(blank=True, help_text="OSM opening_hours grammar string, e.g. 'Mo-Fr 10:00-22:00; Sa 11:00-20:00'.", max_length=512, null=True)),
                ('source', models.CharField(default='firmy', help_text="Data source identifier, e.g. 'firmy'.", max_length=64)),
                ('source_ref', models.CharField(blank=True, help_text='Firmy.cz firmId of the matched business listing.', max_length=64, null=True)),
                ('confidence', models.FloatField(blank=True, help_text='Match confidence in [0, 1] — name similarity blended with geo distance.', null=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('unknown', 'Unknown'), ('pending', 'Pending'), ('error', 'Error')], db_index=True, default='pending', max_length=16)),
                ('error', models.TextField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(blank=True, help_text='When the Firmy.cz fetch completed (None = never fetched).', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pub Hours',
                'verbose_name_plural': 'Pub Hours',
                'ordering': ['-updated_at'],
            },
        ),
    ]
