# Generated by Django 6.0.6 on 2026-06-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubhours',
            name='opening_hours_raw',
            field=models.TextField(blank=True, help_text="OSM opening_hours grammar string, e.g. 'Mo-Fr 10:00-22:00; Sa 11:00-20:00'.", null=True),
        ),
    ]
