# Generated by Django 6.0.6 on 2026-06-09 11:43

import uuid

from django.db import migrations, models

import pubs.models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0002_alter_pubhours_opening_hours_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Stable public account id exposed to the client (not the PK).', unique=True)),
                ('device_id', models.CharField(db_index=True, help_text='Client-generated UUID persisted on the device; the identity anchor.', max_length=64, unique=True)),
                ('token', models.CharField(db_index=True, default=pubs.models.generate_account_token, help_text='Opaque server-issued bearer secret for authenticated calls.', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
