# Generated by Django 6.0.6 on 2026-06-09 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0004_account_token_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, help_text='Geohash-8 of the reported place coordinates.', max_length=12)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='Client-side provider id, e.g. Mapy.cz item id.', max_length=128, null=True)),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.CharField(choices=[('closed', 'Closed / no longer operating'), ('not_pub', 'Not a pub')], db_index=True, max_length=16)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Inactive reports are retained for audit but no longer hide the place.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pub_reports', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Pub Report',
                'verbose_name_plural': 'Pub Reports',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('account', 'cache_key', 'reason'), name='unique_pub_report_per_account_key_reason')],
            },
        ),
    ]
