# Generated by Django 6.0.6 on 2026-06-10 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0005_pubreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, help_text="App version this note describes, e.g. '1.2.0'. Must match the version shipped in the app's app.config.ts.", max_length=32, unique=True)),
                ('title', models.CharField(default='Co je nového', help_text='Headline shown at the top of the popup.', max_length=120)),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Only published notes are returned to the app. Leave off to draft.')),
                ('published_at', models.DateTimeField(blank=True, help_text='Set automatically the first time the note is published.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Release Note',
                'verbose_name_plural': 'Release Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, default='', help_text="Optional emoji shown before the text, e.g. '🍺'.", max_length=8)),
                ('text', models.CharField(help_text="One change in plain Czech, e.g. 'Přidali jsme otevírací dobu hospod.'", max_length=280)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('release_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pubs.releasenote')),
            ],
            options={
                'verbose_name': 'Release Note Item',
                'verbose_name_plural': 'Release Note Items',
                'ordering': ['order', 'id'],
            },
        ),
    ]
