# Generated by Django 6.0.6 on 2026-06-10 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0006_releasenote_releasenoteitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField(help_text='Client-generated UUID; idempotency key for offline retries.')),
                ('category', models.CharField(choices=[('bug', 'Bug'), ('idea', 'Idea'), ('other', 'Other')], db_index=True, max_length=16)),
                ('message', models.TextField(max_length=4000)),
                ('contact_type', models.CharField(blank=True, choices=[('email', 'E-mail'), ('instagram', 'Instagram')], default='', help_text='How the user wants to be reached; empty = no contact given.', max_length=16)),
                ('contact', models.CharField(blank=True, default='', help_text="E-mail address or bare Instagram handle (no leading '@').", max_length=254)),
                ('app_version', models.CharField(blank=True, default='', max_length=64)),
                ('platform', models.CharField(blank=True, default='', max_length=32)),
                ('os_version', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('resolved', 'Resolved')], db_index=True, default='new', max_length=16)),
                ('linear_issue_id', models.CharField(blank=True, default='', max_length=64)),
                ('linear_issue_url', models.URLField(blank=True, default='')),
                ('linear_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_reports', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Feedback Report',
                'verbose_name_plural': 'Feedback Reports',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('account', 'client_id'), name='unique_feedback_per_account_client_id')],
            },
        ),
    ]
