# Generated by Django 6.0.6 on 2026-06-11 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0007_feedbackreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubCommunityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, help_text='Geohash-8 of (lat, lng) — ~38 m precision; matches PubHours.cache_key.', max_length=12, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='Client-side provider id, e.g. Mapy.cz item id.', max_length=128, null=True)),
                ('hours_json', models.JSONField(blank=True, help_text='Structured weekly hours as submitted: {"mo": [["11:00","23:00"]], "tu": [], ...} — all 7 keys mo/tu/we/th/fr/sa/su; an empty list means closed that day. None means no community hours have been contributed yet.', null=True)),
                ('opening_hours_raw', models.TextField(blank=True, default='', help_text='OSM opening_hours grammar string derived from hours_json.')),
                ('beers', models.JSONField(blank=True, default=list, help_text='List of beers on tap: [{"name": str, "price_czk": int|null, "volume_ml": int|null}].')),
                ('hours_updated_at', models.DateTimeField(blank=True, help_text='When opening hours were last contributed (None = never).', null=True)),
                ('beers_updated_at', models.DateTimeField(blank=True, help_text='When the beer list was last contributed (None = never).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, help_text='The most recent contributor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_data', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Pub Community Data',
                'verbose_name_plural': 'Pub Community Data',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PubContributionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, help_text='Geohash-8 of the contributed pub coordinates.', max_length=12)),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('kind', models.CharField(choices=[('hours', 'Opening hours'), ('beers', 'Beers on tap')], db_index=True, max_length=16)),
                ('payload', models.JSONField(help_text='The submitted data for this kind (hours_json dict or beers list).')),
                ('client_id', models.UUIDField(help_text='Client-generated UUID; idempotency key for offline retries.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_logs', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Pub Contribution Log',
                'verbose_name_plural': 'Pub Contribution Log',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('account', 'client_id', 'kind'), name='unique_contribution_per_account_client_id_kind')],
            },
        ),
    ]
