# Generated by Django 6.0.6 on 2026-06-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0008_pubcommunitydata_pubcontributionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubhours',
            name='venue_categories',
            field=models.JSONField(blank=True, default=list, help_text='Firmy.cz category names the classification was derived from.'),
        ),
        migrations.AddField(
            model_name='pubhours',
            name='venue_kind',
            field=models.CharField(choices=[('pub', 'Pub'), ('maybe', 'Maybe'), ('not_pub', 'Not a pub'), ('unknown', 'Unknown')], db_index=True, default='unknown', help_text='Draft-beer classification derived from Firmy.cz categories/tags.', max_length=16),
        ),
    ]
