# Generated by Django 6.0.6 on 2026-06-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0010_release_note_1_1_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubSearchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, help_text='Geohash-5 of the search centre — ~4.9 km cell.', max_length=12)),
                ('radius_bucket', models.PositiveIntegerField(help_text='Smallest covering radius bucket in km (one of 5, 15, 50, 100).')),
                ('items', models.JSONField(blank=True, default=list, help_text='Trimmed Mapy.cz suggest items: [{"name", "label", "position": {"lat", "lon"}, "regionalStructure": [{"name", "type"}, ...]}].')),
                ('fetched_at', models.DateTimeField(help_text='When the upstream Mapy.cz fetch that produced these items completed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pub Search Cache',
                'verbose_name_plural': 'Pub Search Cache',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('cache_key', 'radius_bucket'), name='unique_pub_search_cache_cell_radius')],
            },
        ),
    ]
