# Generated by Django 6.0.6 on 2026-06-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0011_pubsearchcache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubsearchcache',
            name='cache_key',
            field=models.CharField(db_index=True, help_text='Geohash-6 of the request coordinate — ~1.2 km × 0.6 km cell.', max_length=12),
        ),
    ]
