# Generated by Django 6.0.6 on 2026-06-12 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0011_pubsearchcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField(help_text='Client-generated UUID; idempotency key for offline retries.')),
                ('cache_key', models.CharField(db_index=True, help_text='Geohash-8 of (lat, lng) — ~38 m precision; matches PubCommunityData.cache_key.', max_length=12)),
                ('name', models.TextField(help_text='Pub name as the client saw it (1..200 chars, enforced by the serializer).')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('city', models.TextField(blank=True, default='', help_text='Optional city hint from the client.')),
                ('external_id', models.TextField(blank=True, default='', help_text='Client-side provider id, e.g. Mapy.cz item id.')),
                ('beer_name', models.TextField(help_text='Beer name (1..80 chars, enforced by the serializer).')),
                ('price_czk', models.PositiveSmallIntegerField(help_text='Price paid in CZK (1..1000) — mandatory; this is the community-sourcing hook.')),
                ('volume_ml', models.PositiveSmallIntegerField(blank=True, help_text='Glass volume in ml (one of 300/330/400/500/1000) or null if unknown.', null=True)),
                ('drank_at', models.DateTimeField(help_text='When the beer was drunk (client-supplied ISO8601, or server now() if omitted).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(help_text='The user who logged this drink.', on_delete=django.db.models.deletion.CASCADE, related_name='drinks', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Drink Log',
                'verbose_name_plural': 'Drink Log',
                'ordering': ['-drank_at'],
                'indexes': [models.Index(fields=['account', 'drank_at'], name='pubs_drinkl_account_e02ef0_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'client_id'), name='unique_drink_per_account_client_id')],
            },
        ),
    ]
