# Generated by Django 6.0.6 on 2026-06-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pubs", "0012_drinklog"),
        ("pubs", "0012_update_pub_search_cache_geohash6_help"),
    ]

    operations = []
