# Generated by Django 6.0.6 on 2026-06-13 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0013_merge_drinklog_pub_search_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_open_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('app_foreground_count', models.PositiveIntegerField(default=0)),
                ('walked_distance_m', models.PositiveIntegerField(db_index=True, default=0)),
                ('client_warning_count', models.PositiveIntegerField(default=0)),
                ('client_error_count', models.PositiveIntegerField(default=0)),
                ('api_failure_count', models.PositiveIntegerField(default=0)),
                ('last_app_open_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_app_version', models.CharField(blank=True, default='', max_length=64)),
                ('last_platform', models.CharField(blank=True, default='', max_length=32)),
                ('last_os_version', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage_stats', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Account Usage Stats',
                'verbose_name_plural': 'Account Usage Stats',
                'ordering': ['-walked_distance_m', '-app_open_count'],
            },
        ),
        migrations.CreateModel(
            name='ClientEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('app_open', 'App opened'), ('app_foreground', 'App foregrounded'), ('walking_distance', 'Walking distance'), ('console_warn', 'Console warning'), ('console_error', 'Console error'), ('unhandled_error', 'Unhandled error'), ('api_failure', 'API failure')], db_index=True, max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='info', max_length=16)),
                ('message', models.CharField(blank=True, default='', max_length=300)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('app_version', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('platform', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('os_version', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(blank=True, help_text='Anonymous account when the app had a valid token; null for unauthenticated telemetry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_events', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Client Event',
                'verbose_name_plural': 'Client Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'created_at'], name='pubs_client_event_344958_idx'), models.Index(fields=['severity', 'created_at'], name='pubs_client_severit_4d0fb6_idx'), models.Index(fields=['account', 'created_at'], name='pubs_client_account_c736c4_idx')],
            },
        ),
    ]
