# Generated by Django 6.0.6 on 2026-06-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0014_accountusagestats_clientevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubhours',
            name='rating_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of public user ratings behind rating_value.', null=True),
        ),
        migrations.AddField(
            model_name='pubhours',
            name='rating_label',
            field=models.CharField(blank=True, help_text="Human rating label from the source listing, e.g. 'Velmi dobré'.", max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='pubhours',
            name='rating_value',
            field=models.FloatField(blank=True, help_text='Public star rating from the source listing, e.g. 4.1.', null=True),
        ),
    ]
