# Generated by Django 6.0.6 on 2026-06-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0017_stale_ratingless_firmy_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientevent',
            name='event',
            field=models.CharField(choices=[('app_open', 'App opened'), ('app_foreground', 'App foregrounded'), ('walking_distance', 'Walking distance'), ('counter_tab_opened', 'Counter tab opened'), ('counter_session_started', 'Counter session started'), ('drink_added', 'Drink added'), ('drink_removed', 'Drink removed'), ('drink_synced', 'Drink synced'), ('drink_sync_failed', 'Drink sync failed'), ('beer_form_opened', 'Beer form opened'), ('beer_price_added', 'Beer price added'), ('counter_returned_same_day', 'Counter returned same day'), ('counter_returned_later', 'Counter returned later'), ('console_warn', 'Console warning'), ('console_error', 'Console error'), ('unhandled_error', 'Unhandled error'), ('api_failure', 'API failure')], db_index=True, max_length=64),
        ),
    ]
