# Generated by Codex on 2026-06-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pubs", "0018_alter_clientevent_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="hide_pub_names",
            field=models.BooleanField(
                default=False,
                help_text="Whether the app should hide pub names behind the reveal interaction.",
            ),
        ),
    ]
