# Generated by Django 6.0.6 on 2026-06-14 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0019_account_hide_pub_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, help_text='Geohash-8 of (lat, lng) — ~38 m precision; matches PubHours.cache_key.', max_length=12)),
                ('name', models.TextField(blank=True, default='', help_text='Pub name as the client saw it (legacy ratings may have none).')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('external_id', models.TextField(blank=True, default='', help_text='Client-side provider id, e.g. Mapy.cz item id.')),
                ('verdict', models.CharField(blank=True, choices=[('like', 'Like'), ('dislike', 'Dislike')], default='', help_text='Thumbs verdict: "like" / "dislike" / "" (none).', max_length=10)),
                ('tag', models.TextField(blank=True, default='', help_text='Optional one-word tag (<=64 chars, enforced by the serializer).')),
                ('note', models.TextField(blank=True, default='', help_text='Optional free-text note (<=280 chars, enforced by the serializer).')),
                ('client_updated_at', models.DateTimeField(help_text="Client's local updatedAt; the last-write-wins conflict key.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='The user who owns this private rating.', on_delete=django.db.models.deletion.CASCADE, related_name='pub_ratings', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Pub Rating',
                'verbose_name_plural': 'Pub Ratings',
                'ordering': ['-client_updated_at'],
                'constraints': [models.UniqueConstraint(fields=('account', 'cache_key'), name='unique_rating_per_account_pub')],
            },
        ),
        migrations.CreateModel(
            name='PubVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField(help_text='Client-generated UUID; idempotency key for offline retries / updates.')),
                ('cache_key', models.CharField(db_index=True, help_text='Geohash-8 of (lat, lng) — ~38 m precision; matches PubHours.cache_key.', max_length=12)),
                ('name', models.TextField(help_text='Pub name as the client saw it.')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('city', models.TextField(blank=True, default='', help_text='Optional city hint from the client.')),
                ('external_id', models.TextField(blank=True, default='', help_text='Client-side provider id, e.g. Mapy.cz item id.')),
                ('started_at', models.DateTimeField(help_text='When the evening began — the identity of the visit.')),
                ('ended_at', models.DateTimeField(blank=True, help_text='When the evening ended (None = still open / unknown).', null=True)),
                ('client_updated_at', models.DateTimeField(help_text="Client's local updatedAt; the last-write-wins conflict key.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='The user who made this visit.', on_delete=django.db.models.deletion.CASCADE, related_name='pub_visits', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Pub Visit',
                'verbose_name_plural': 'Pub Visits',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['account', 'started_at'], name='pubs_pubvis_account_bddcdf_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'client_id'), name='unique_visit_per_account_client_id')],
            },
        ),
    ]
