# Generated by Django 6.0.6 on 2026-06-14 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0021_alter_clientevent_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddedPub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField(db_index=True, help_text='Client-generated UUID; idempotency key for offline retries.')),
                ('cache_key', models.CharField(db_index=True, help_text='Geohash-8 of (lat, lng) — ~38 m precision. Indexed but NOT unique: identity is (account, client_id), so two different pubs in the same cell coexist.', max_length=12)),
                ('name', models.TextField(help_text='Pub name as submitted by the client.')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('city', models.TextField(blank=True, default='')),
                ('address', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Inactive rows are kept for audit but hidden from /v1/pubs/near.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, help_text='The account that submitted this pub.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_pubs', to='pubs.account')),
            ],
            options={
                'verbose_name': 'User Added Pub',
                'verbose_name_plural': 'User Added Pubs',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['active', 'lat', 'lng'], name='addedpub_active_latlng_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'client_id'), name='unique_added_pub_per_account_client_id')],
            },
        ),
    ]
