# Generated by Django 6.0.6 on 2026-06-15 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0023_release_note_1_1_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When deletion was requested. Hard purge happens after the grace window.', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Optional display name, set on sign-up or from a social provider.', max_length=120),
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending_deletion', 'Pending deletion')], db_index=True, default='active', help_text='ACTIVE, or PENDING_DELETION during the soft-delete grace window.', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='token_hash',
            field=models.CharField(blank=True, help_text='DEPRECATED — superseded by AuthToken. SHA-256 digest of the legacy single bearer token; nullable, kept for backwards compatibility.', max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(help_text='SHA-256 hex digest of the raw bearer token.', max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('device', 'Device'), ('session', 'Session')], default='session', max_length=16)),
                ('device_label', models.CharField(blank=True, default='', help_text="Optional human label, e.g. 'iPhone 16 / app 1.2'.", max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional absolute expiry. NULL = never expires (revoke by row).', null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Auth token',
                'verbose_name_plural': 'Auth tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Normalized (lowercase) login email; globally unique.', max_length=254, unique=True)),
                ('password', models.CharField(help_text='Django password-hash string (Argon2).', max_length=128)),
                ('email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_credential', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Email credential',
                'verbose_name_plural': 'Email credentials',
            },
        ),
        migrations.CreateModel(
            name='OneTimeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('verify_email', 'Verify email'), ('reset_password', 'Reset password')], max_length=20)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_tokens', to='pubs.account')),
            ],
            options={
                'verbose_name': 'One-time token',
                'verbose_name_plural': 'One-time tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('apple', 'Apple')], db_index=True, max_length=20)),
                ('subject', models.CharField(help_text="Provider 'sub' claim — the stable per-provider user id.", max_length=255)),
                ('email', models.EmailField(blank=True, default='', help_text='Email asserted by the provider at link time (snapshot).', max_length=254)),
                ('apple_refresh_token', models.CharField(blank=True, default='', help_text='Apple refresh token, stored so the token can be revoked at account deletion (Apple requires revocation). Empty for Google.', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Auth identity',
                'verbose_name_plural': 'Auth identities',
                'constraints': [models.UniqueConstraint(fields=('provider', 'subject'), name='uniq_provider_subject'), models.UniqueConstraint(fields=('account', 'provider'), name='uniq_account_provider')],
            },
        ),
    ]
