# Generated by Django 6.0.6 on 2026-06-15 14:10

import django.db.models.functions.text
from django.db import migrations, models

import pubs.models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0025_backfill_auth_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, default='', help_text='Uploaded profile picture, stored on local disk as a 256px square webp. Empty when the account has no avatar (client renders an initials fallback).', max_length=255, upload_to=pubs.models.account_avatar_path),
        ),
        migrations.AddField(
            model_name='account',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, help_text='Public profile (opt-out). Gates global search and leaderboards; friends always see the profile regardless.'),
        ),
        migrations.AddField(
            model_name='account',
            name='nickname',
            field=models.CharField(blank=True, db_index=True, help_text='Unique public handle (3–20 chars [a-zA-Z0-9_.]), user-picked. Casing is preserved; uniqueness is case-insensitive via the uniq_account_nickname_ci functional constraint. NULL for accounts that have not set one yet.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Optional real name (free text).', max_length=120),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nickname'), condition=models.Q(models.Q(('nickname', ''), _negated=True), ('nickname__isnull', False)), name='uniq_account_nickname_ci'),
        ),
    ]
