# Generated by Codex on 2026-06-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pubs", "0026_account_profile_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="compass_mode",
            field=models.CharField(
                choices=[("nearest", "Nearest"), ("surprise", "Surprise")],
                default="nearest",
                help_text="Preferred compass mode in the mobile app.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="max_distance_km",
            field=models.FloatField(
                blank=True,
                help_text="Preferred search radius in kilometres; null means unlimited.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="price_currency",
            field=models.CharField(
                choices=[("CZK", "CZK"), ("EUR", "EUR")],
                default="CZK",
                help_text="Preferred currency for displaying counted beer totals.",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="haptic_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Whether haptic feedback is enabled in the mobile app.",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="sound_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether counter sounds are enabled in the mobile app.",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="hide_closed_pubs",
            field=models.BooleanField(
                default=True,
                help_text="Whether known-closed pubs should be hidden in the mobile app.",
            ),
        ),
    ]
