# Generated by Django 6.0.6 on 2026-06-15 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0027_account_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='marketing_emails_enabled',
            field=models.BooleanField(default=False, help_text='Whether the user opted in to product/marketing e-mails.'),
        ),
        migrations.AddField(
            model_name='account',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiry reported by a verified subscription provider, when available.', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='subscription_original_transaction_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Stable store purchase id used for future restore-purchases verification.', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='subscription_platform',
            field=models.CharField(blank=True, default='', help_text='Store platform for the latest known purchase, e.g. apple or google.', max_length=16),
        ),
        migrations.AddField(
            model_name='account',
            name='subscription_product_id',
            field=models.CharField(blank=True, default='', help_text='Store product id for the latest known purchase.', max_length=128),
        ),
        migrations.AddField(
            model_name='account',
            name='subscription_status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('pending_verification', 'Pending verification'), ('active', 'Active'), ('grace_period', 'Grace period'), ('expired', 'Expired')], db_index=True, default='inactive', help_text='Current subscription state; pending_verification means restore data was received.', max_length=32),
        ),
        migrations.AddField(
            model_name='account',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free'), ('plus', 'Na Pivo+')], db_index=True, default='free', help_text='Current entitlement tier. Free until a receipt is verified.', max_length=16),
        ),
        migrations.AddField(
            model_name='account',
            name='subscription_updated_at',
            field=models.DateTimeField(blank=True, help_text='When subscription metadata last changed.', null=True),
        ),
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate_nickname', 'Inappropriate nickname'), ('inappropriate_avatar', 'Inappropriate avatar'), ('impersonation', 'Impersonation'), ('spam', 'Spam'), ('other', 'Other')], db_index=True, max_length=32)),
                ('comment', models.TextField(blank=True, default='', max_length=1000)),
                ('target_snapshot', models.JSONField(blank=True, default=dict, help_text='Nickname/display/avatar/is_public snapshot at report time.')),
                ('status', models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], db_index=True, default='new', max_length=16)),
                ('moderator_note', models.TextField(blank=True, default='')),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_reports_made', to='pubs.account')),
                ('target_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_reports_received', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Content Report',
                'verbose_name_plural': 'Content Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_account', 'status', 'created_at'], name='pubs_conten_target__a9c08b_idx'), models.Index(fields=['reporter', 'created_at'], name='pubs_conten_reporte_3252ae_idx')],
            },
        ),
    ]
