# Generated by Django 6.0.6 on 2026-06-22 15:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0031_seed_beer_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinklog',
            name='beer_product_key',
            field=models.SlugField(blank=True, default='', help_text='Denormalized BeerProduct.key for future stats/filter queries.', max_length=100),
        ),
        migrations.AddField(
            model_name='drinklog',
            name='beer_product_name',
            field=models.CharField(blank=True, default='', help_text='Denormalized BeerProduct.name as it was at log time.', max_length=160),
        ),
        migrations.CreateModel(
            name='BeerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable ASCII identifier, e.g. velkopopovicky-kozel-11.', max_length=100, unique=True)),
                ('brand_key', models.SlugField(max_length=80)),
                ('brand_name', models.CharField(max_length=120)),
                ('name', models.CharField(help_text='Canonical beer product display name.', max_length=160)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Common typed aliases used for matching and suggestions.')),
                ('rank', models.PositiveSmallIntegerField(db_index=True, default=1000, help_text='Lower ranks appear earlier in suggestions.')),
                ('source_label', models.CharField(blank=True, default='', max_length=160)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pubs.beerbrand')),
            ],
            options={
                'verbose_name': 'Beer Product',
                'verbose_name_plural': 'Beer Products',
                'ordering': ['rank', 'name'],
            },
        ),
        migrations.AddField(
            model_name='drinklog',
            name='beer_product',
            field=models.ForeignKey(blank=True, help_text='Matched canonical product, if the submitted beer name was recognized.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drinks', to='pubs.beerproduct'),
        ),
        migrations.CreateModel(
            name='PubBeerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, help_text='Geohash-8 of (lat, lng) — matches PubCommunityData.cache_key.', max_length=12)),
                ('name', models.TextField(help_text='Pub name as submitted by the client.')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('city', models.TextField(blank=True, default='')),
                ('external_id', models.TextField(blank=True, default='')),
                ('brand_key', models.SlugField(max_length=80)),
                ('brand_name', models.CharField(max_length=120)),
                ('product_key', models.SlugField(max_length=100)),
                ('product_name', models.CharField(max_length=160)),
                ('last_price_czk', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_volume_ml', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('community', 'Community menu'), ('drink', 'Drink log')], max_length=16)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pub_beer_products', to='pubs.account')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pub_product_links', to='pubs.beerbrand')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pub_links', to='pubs.beerproduct')),
            ],
            options={
                'verbose_name': 'Pub Beer Product',
                'verbose_name_plural': 'Pub Beer Products',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.AddIndex(
            model_name='beerproduct',
            index=models.Index(fields=['brand_key', 'active'], name='pubs_beerpr_brand_k_04ab3a_idx'),
        ),
        migrations.AddIndex(
            model_name='pubbeerproduct',
            index=models.Index(fields=['brand_key', 'active'], name='pubs_pubbee_brand_k_595a90_idx'),
        ),
        migrations.AddIndex(
            model_name='pubbeerproduct',
            index=models.Index(fields=['product_key', 'active'], name='pubs_pubbee_product_1d95b4_idx'),
        ),
        migrations.AddIndex(
            model_name='pubbeerproduct',
            index=models.Index(fields=['cache_key', 'active'], name='pubs_pubbee_cache_k_104d73_idx'),
        ),
        migrations.AddConstraint(
            model_name='pubbeerproduct',
            constraint=models.UniqueConstraint(fields=('cache_key', 'product'), name='unique_pub_beer_product'),
        ),
    ]
