# Generated by Django 6.0.6 on 2026-06-23 20:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0035_pubhours_garden_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable ASCII id, e.g. payment_card, seating_garden, game_darts. NEVER renamed/reused.', max_length=40, unique=True)),
                ('label', models.CharField(help_text="Czech display label, e.g. 'Platba kartou'.", max_length=80)),
                ('short_label', models.CharField(blank=True, default='', help_text='Optional compact chip label.', max_length=40)),
                ('icon', models.CharField(blank=True, default='', help_text="IconGlyph export name the client renders, e.g. 'CreditCardIcon'. NO emoji.", max_length=40)),
                ('group', models.CharField(choices=[('payment', 'Platba'), ('seating', 'Posezení'), ('games', 'Zábava'), ('atmosphere', 'Atmosféra'), ('practical', 'Praktické')], db_index=True, max_length=16)),
                ('rank', models.PositiveSmallIntegerField(db_index=True, default=1000, help_text='Lower ranks render earlier.')),
                ('filter_candidate', models.BooleanField(default=True, help_text='Whether this is a planned map-filter facet (design signal; filter is future).')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Amenity Kind',
                'verbose_name_plural': 'Amenity Kinds',
                'ordering': ['rank', 'key'],
            },
        ),
        migrations.CreateModel(
            name='PubAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, help_text='Geohash-8 of (lat, lng) — matches PubAmenityVote / PubHours.', max_length=12)),
                ('amenity_key', models.SlugField(max_length=40)),
                ('name', models.TextField(blank=True, default='')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('city', models.TextField(blank=True, default='')),
                ('external_id', models.TextField(blank=True, default='')),
                ('yes_count', models.PositiveIntegerField(default=0)),
                ('no_count', models.PositiveIntegerField(default=0)),
                ('distinct_voter_count', models.PositiveIntegerField(default=0, help_text='Distinct accounts that have a live vote here (one per account by unique constraint).')),
                ('status', models.CharField(choices=[('yes', 'Has it'), ('no', "Doesn't have it"), ('disputed', 'Disputed'), ('unknown', 'Not enough votes')], db_index=True, default='unknown', max_length=10)),
                ('confidence', models.FloatField(default=0.0, help_text='0.0–1.0 agreement×volume score; stored (indexable), recomputed on write. See §5.4.')),
                ('first_mapped_at', models.DateTimeField(blank=True, help_text='Server time the first vote created this row. Immutable.', null=True)),
                ('last_updated', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Server time of the last vote that touched this aggregate.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_mapper', models.ForeignKey(blank=True, help_text='Account that created this aggregate row (the FIRST vote). IMMUTABLE — never reattributed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amenities_first_mapped', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Pub Amenity',
                'verbose_name_plural': 'Pub Amenities',
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['amenity_key', 'status'], name='pubs_pubame_amenity_364abf_idx'), models.Index(fields=['cache_key'], name='pubs_pubame_cache_k_6b1c2e_idx')],
                'constraints': [models.UniqueConstraint(fields=('cache_key', 'amenity_key'), name='unique_pub_amenity')],
            },
        ),
        migrations.CreateModel(
            name='PubAmenityVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, help_text='Geohash-8 of (lat, lng) — matches PubHours / PubRating.cache_key.', max_length=12)),
                ('amenity_key', models.SlugField(help_text='AmenityKind.key this vote is about.', max_length=40)),
                ('name', models.TextField(blank=True, default='', help_text='Pub name as the client saw it.')),
                ('lat', models.FloatField(help_text='Server-side only: derives cache_key; never exposed in reads.')),
                ('lng', models.FloatField(help_text='Server-side only: derives cache_key; never exposed in reads.')),
                ('city', models.TextField(blank=True, default='')),
                ('external_id', models.TextField(blank=True, default='', help_text='Client provider id (Mapy item id).')),
                ('value', models.CharField(choices=[('yes', 'Has it'), ('no', "Doesn't have it")], help_text='"yes" | "no". A retraction deletes the row instead of storing empty.', max_length=3)),
                ('awarded_xp', models.PositiveIntegerField(default=0, help_text='XP this row has EVER paid out. Gates idempotent XP — a flip/re-vote pays 0 (§7.3).')),
                ('client_updated_at', models.DateTimeField(help_text="Client's local updatedAt; the last-write-wins conflict key (per amenity).")),
                ('taxonomy_version', models.PositiveSmallIntegerField(blank=True, help_text='Which bundled taxonomy version the client captured this vote under (mobile CURRENT_TAXONOMY_VERSION). Optional, analytics-only — NEVER a validation gate. Lets us spot votes cast under an old amenity set and drive future re-check nudges. Absent (legacy/unknown clients) is fine.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='The user who cast this vote.', on_delete=django.db.models.deletion.CASCADE, related_name='amenity_votes', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Pub Amenity Vote',
                'verbose_name_plural': 'Pub Amenity Votes',
                'ordering': ['-client_updated_at'],
                'indexes': [models.Index(fields=['account', 'cache_key'], name='pubs_pubame_account_a33989_idx'), models.Index(fields=['cache_key', 'amenity_key'], name='pubs_pubame_cache_k_281a51_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'cache_key', 'amenity_key'), name='unique_amenity_vote_per_account_pub')],
            },
        ),
    ]
