# Generated by Django 6.0.6 on 2026-06-23 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0038_accountusagestats_amenity_votes_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPubCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pub_completions', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Account Pub Completion',
                'verbose_name_plural': 'Account Pub Completions',
                'constraints': [models.UniqueConstraint(fields=('account', 'cache_key'), name='unique_account_pub_completion')],
            },
        ),
        migrations.CreateModel(
            name='AmenityXpLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=12)),
                ('amenity_key', models.SlugField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_xp_ledger', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Amenity XP Ledger',
                'verbose_name_plural': 'Amenity XP Ledger',
                'indexes': [models.Index(fields=['account', 'cache_key'], name='pubs_amenit_account_fb26c3_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'cache_key', 'amenity_key'), name='unique_amenity_xp_ledger')],
            },
        ),
    ]
