# Generated by Django 6.0.6 on 2026-06-24 08:38

import django.db.models.deletion
from django.db import migrations, models


def backfill_pub_identity_keys(apps, schema_editor):
    for model_name in [
        "AccountPubCompletion",
        "AmenityXpLedger",
        "PubAmenity",
        "PubAmenityVote",
    ]:
        Model = apps.get_model("pubs", model_name)
        for row in Model.objects.filter(pub_identity_key="").iterator():
            row.pub_identity_key = row.cache_key
            row.save(update_fields=["pub_identity_key"])


def deactivate_smoking_amenity(apps, schema_editor):
    AmenityKind = apps.get_model("pubs", "AmenityKind")
    AmenityKind.objects.filter(key="atmosphere_smoking").update(active=False)


def reactivate_smoking_amenity(apps, schema_editor):
    AmenityKind = apps.get_model("pubs", "AmenityKind")
    AmenityKind.objects.filter(key="atmosphere_smoking").update(active=True)


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0040_deactivate_unused_amenity_kinds'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMappedPub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=12)),
                ('pub_identity_key', models.CharField(db_index=True, default='', max_length=320)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Account Mapped Pub',
                'verbose_name_plural': 'Account Mapped Pubs',
            },
        ),
        migrations.CreateModel(
            name='PubAmenityVoteTombstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=12)),
                ('pub_identity_key', models.CharField(db_index=True, default='', max_length=320)),
                ('amenity_key', models.SlugField(max_length=40)),
                ('name', models.TextField(blank=True, default='')),
                ('client_updated_at', models.DateTimeField(help_text='Client timestamp of the latest retraction for LWW conflict checks.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pub Amenity Vote Tombstone',
                'verbose_name_plural': 'Pub Amenity Vote Tombstones',
                'ordering': ['-client_updated_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='accountpubcompletion',
            name='unique_account_pub_completion',
        ),
        migrations.RemoveConstraint(
            model_name='amenityxpledger',
            name='unique_amenity_xp_ledger',
        ),
        migrations.RemoveConstraint(
            model_name='pubamenity',
            name='unique_pub_amenity',
        ),
        migrations.RemoveConstraint(
            model_name='pubamenityvote',
            name='unique_amenity_vote_per_account_pub',
        ),
        migrations.RemoveIndex(
            model_name='amenityxpledger',
            name='pubs_amenit_account_fb26c3_idx',
        ),
        migrations.RemoveIndex(
            model_name='pubamenityvote',
            name='pubs_pubame_cache_k_281a51_idx',
        ),
        migrations.AddField(
            model_name='accountpubcompletion',
            name='pub_identity_key',
            field=models.CharField(db_index=True, default='', max_length=320),
        ),
        migrations.AddField(
            model_name='amenityxpledger',
            name='pub_identity_key',
            field=models.CharField(db_index=True, default='', max_length=320),
        ),
        migrations.AddField(
            model_name='pubamenity',
            name='pub_identity_key',
            field=models.CharField(db_index=True, default='', help_text='cache_key plus normalized pub name; aggregate identity for one business.', max_length=320),
        ),
        migrations.AddField(
            model_name='pubamenityvote',
            name='pub_identity_key',
            field=models.CharField(db_index=True, default='', help_text='cache_key plus normalized pub name; separates businesses sharing one geohash cell.', max_length=320),
        ),
        migrations.RunPython(backfill_pub_identity_keys, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='amenityxpledger',
            index=models.Index(fields=['account', 'pub_identity_key'], name='pubs_amenit_account_18a2e0_idx'),
        ),
        migrations.AddIndex(
            model_name='pubamenity',
            index=models.Index(fields=['pub_identity_key', 'amenity_key'], name='pubs_pubame_pub_ide_ea42d9_idx'),
        ),
        migrations.AddIndex(
            model_name='pubamenityvote',
            index=models.Index(fields=['pub_identity_key', 'amenity_key'], name='pubs_pubame_pub_ide_05068e_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountpubcompletion',
            constraint=models.UniqueConstraint(fields=('account', 'pub_identity_key'), name='unique_account_pub_completion'),
        ),
        migrations.AddConstraint(
            model_name='amenityxpledger',
            constraint=models.UniqueConstraint(fields=('account', 'pub_identity_key', 'amenity_key'), name='unique_amenity_xp_ledger'),
        ),
        migrations.AddConstraint(
            model_name='pubamenity',
            constraint=models.UniqueConstraint(fields=('pub_identity_key', 'amenity_key'), name='unique_pub_amenity'),
        ),
        migrations.AddConstraint(
            model_name='pubamenityvote',
            constraint=models.UniqueConstraint(fields=('account', 'pub_identity_key', 'amenity_key'), name='unique_amenity_vote_per_account_pub'),
        ),
        migrations.AddField(
            model_name='accountmappedpub',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapped_pubs', to='pubs.account'),
        ),
        migrations.AddField(
            model_name='pubamenityvotetombstone',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_vote_tombstones', to='pubs.account'),
        ),
        migrations.AddConstraint(
            model_name='accountmappedpub',
            constraint=models.UniqueConstraint(fields=('account', 'pub_identity_key'), name='unique_account_mapped_pub'),
        ),
        migrations.AddIndex(
            model_name='pubamenityvotetombstone',
            index=models.Index(fields=['account', 'cache_key'], name='pubs_pubame_account_8928cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='pubamenityvotetombstone',
            constraint=models.UniqueConstraint(fields=('account', 'pub_identity_key', 'amenity_key'), name='unique_amenity_vote_tombstone'),
        ),
        migrations.RunPython(deactivate_smoking_amenity, reactivate_smoking_amenity),
    ]
