# Generated by Django 6.0.6 on 2026-06-24 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0041_amenity_identity_tombstones'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubCommunityXpLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=12)),
                ('kind', models.CharField(choices=[('hours', 'Opening hours'), ('beers', 'Beers on tap')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_xp_ledger', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Pub Community XP Ledger',
                'verbose_name_plural': 'Pub Community XP Ledger',
                'constraints': [models.UniqueConstraint(fields=('account', 'cache_key', 'kind'), name='unique_pub_community_xp_ledger')],
            },
        ),
    ]
