# Generated by Django 6.0.6 on 2026-06-26 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0043_release_note_1_2_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_token', models.CharField(help_text='Expo push token. Needed to send notifications; never log it.', max_length=512, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=16)),
                ('permission_status', models.CharField(choices=[('granted', 'Granted'), ('denied', 'Denied'), ('undetermined', 'Undetermined')], db_index=True, default='undetermined', max_length=16)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('app_version', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_registered_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Push device',
                'verbose_name_plural': 'Push devices',
                'ordering': ['-last_registered_at'],
                'indexes': [models.Index(fields=['account', 'enabled'], name='pubs_pushde_account_71e63e_idx'), models.Index(fields=['platform', 'enabled'], name='pubs_pushde_platfor_f6a9f6_idx')],
            },
        ),
    ]
