# Generated by Django 6.0.6 on 2026-06-26 17:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0044_pushdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendPubActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('client_id', models.UUIDField(help_text='Client-generated idempotency key for the shared pub session.')),
                ('cache_key', models.CharField(db_index=True, max_length=12)),
                ('name', models.TextField(help_text='Pub name as the client saw it.')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('city', models.TextField(blank=True, default='')),
                ('external_id', models.TextField(blank=True, default='')),
                ('message', models.CharField(blank=True, default='', max_length=160)),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_pub_activities', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Friend pub activity',
                'verbose_name_plural': 'Friend pub activities',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], db_index=True, default='pending', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friendships', to='pubs.account')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friendships', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Friendship',
                'verbose_name_plural': 'Friendships',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FriendNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('friend_request', 'Friend request'), ('friend_accepted', 'Friend accepted'), ('friend_at_pub', 'Friend at pub')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(max_length=240)),
                ('pub_cache_key', models.CharField(blank=True, default='', max_length=12)),
                ('pub_name', models.CharField(blank=True, default='', max_length=200)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friend_notifications_sent', to='pubs.account')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_notifications', to='pubs.account')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='pubs.friendpubactivity')),
                ('friendship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='pubs.friendship')),
            ],
            options={
                'verbose_name': 'Friend notification',
                'verbose_name_plural': 'Friend notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='friendpubactivity',
            index=models.Index(fields=['account', 'active', 'expires_at'], name='pubs_friend_account_6619ba_idx'),
        ),
        migrations.AddIndex(
            model_name='friendpubactivity',
            index=models.Index(fields=['cache_key', 'active', 'expires_at'], name='pubs_friend_cache_k_1c8299_idx'),
        ),
        migrations.AddConstraint(
            model_name='friendpubactivity',
            constraint=models.UniqueConstraint(fields=('account', 'client_id'), name='unique_friend_activity_per_account_client_id'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['requester', 'status'], name='pubs_friend_request_737cba_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['recipient', 'status'], name='pubs_friend_recipie_94933e_idx'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('requester', 'recipient'), name='unique_directed_friendship'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.CheckConstraint(condition=models.Q(('requester', models.F('recipient')), _negated=True), name='friendship_no_self_request'),
        ),
        migrations.AddIndex(
            model_name='friendnotification',
            index=models.Index(fields=['recipient', 'read_at', 'created_at'], name='pubs_friend_recipie_c0f63d_idx'),
        ),
        migrations.AddIndex(
            model_name='friendnotification',
            index=models.Index(fields=['recipient', 'kind', 'created_at'], name='pubs_friend_recipie_0c03a2_idx'),
        ),
    ]
