# Generated by Django 6.0.6 on 2026-06-29 21:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0045_friendpubactivity_friendship_friendnotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ghost_mode',
            field=models.BooleanField(default=False, help_text='Hide my broadcast from friends: keep my own activity but skip fanout + feed visibility.'),
        ),
        migrations.AddField(
            model_name='account',
            name='quiet_hours_enabled',
            field=models.BooleanField(default=True, help_text='Whether friend pushes are suppressed during the local quiet-hours window.'),
        ),
        migrations.AddField(
            model_name='account',
            name='quiet_hours_end',
            field=models.PositiveSmallIntegerField(default=9, help_text='Local Europe/Prague hour (0-23) the quiet window ends, exclusive.'),
        ),
        migrations.AddField(
            model_name='account',
            name='quiet_hours_start',
            field=models.PositiveSmallIntegerField(default=23, help_text='Local Europe/Prague hour (0-23) the quiet window starts, inclusive.'),
        ),
        migrations.AlterField(
            model_name='friendnotification',
            name='kind',
            field=models.CharField(choices=[('friend_request', 'Friend request'), ('friend_accepted', 'Friend accepted'), ('friend_at_pub', 'Friend at pub'), ('friend_rsvp', 'Friend RSVP')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='FriendActivityResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('response', models.CharField(choices=[('going', 'Going'), ('maybe', 'Maybe'), ('cant', "Can't")], default='going', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_responses', to='pubs.account')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='pubs.friendpubactivity')),
            ],
            options={
                'verbose_name': 'Friend activity response',
                'verbose_name_plural': 'Friend activity responses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['activity', 'response'], name='pubs_friend_activit_9ae401_idx')],
                'constraints': [models.UniqueConstraint(fields=('activity', 'account'), name='unique_activity_response_per_account')],
            },
        ),
    ]
