# Generated by merge of parallel migration branches.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pubs", "0046_account_ghost_mode_account_quiet_hours_enabled_and_more"),
        ("pubs", "0046_release_note_1_2_1"),
    ]

    operations = []
