# Generated by Django 6.0.6 on 2026-07-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0048_add_counter_session_telemetry_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendpubactivity',
            name='kind',
            field=models.CharField(choices=[('live', 'Live'), ('plan', 'Plan')], db_index=True, default='live', help_text='live = broadcasting now; plan = a future intent to convert to live.', max_length=8),
        ),
        migrations.AddField(
            model_name='friendpubactivity',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the afternoon plan reminder was pushed, so it fires once.', null=True),
        ),
        migrations.AddField(
            model_name='friendpubactivity',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, db_index=True, help_text="Target time for a plan (the 'Dnes v 20:00'); NULL for live rows.", null=True),
        ),
        migrations.AddIndex(
            model_name='friendpubactivity',
            index=models.Index(fields=['kind', 'active', 'scheduled_for'], name='pubs_friend_kind_495cd7_idx'),
        ),
        migrations.AddIndex(
            model_name='friendpubactivity',
            index=models.Index(fields=['account', 'kind', 'active', 'scheduled_for'], name='pubs_friend_account_21fdf7_idx'),
        ),
    ]
