# Generated by Django 6.0.6 on 2026-07-02 10:12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0049_friend_activity_kind_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendActivityReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('cheers', 'Cheers')], default='cheers', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_reactions', to='pubs.account')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='pubs.friendpubactivity')),
            ],
            options={
                'verbose_name': 'Friend activity reaction',
                'verbose_name_plural': 'Friend activity reactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['activity', 'kind'], name='pubs_friend_activit_48eba9_idx')],
                'constraints': [models.UniqueConstraint(fields=('activity', 'account'), name='unique_reaction_per_account')],
            },
        ),
    ]
