# Generated by Django 6.0.6 on 2026-07-02 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0050_friend_activity_reaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendInviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Opaque random invite code, ~72 bits (secrets.token_urlsafe(9)).', max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Friend invite code',
                'verbose_name_plural': 'Friend invite codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'revoked', 'expires_at'], name='pubs_friend_account_5e3fcc_idx')],
            },
        ),
    ]
