# Generated by Django 6.0.6 on 2026-07-02 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0051_friend_invite_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to='pubs.account')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Friend block',
                'verbose_name_plural': 'Friend blocks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blocker'], name='pubs_friend_blocker_95f38b_idx'), models.Index(fields=['blocked'], name='pubs_friend_blocked_e74429_idx')],
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_block_pair'), models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='block_no_self')],
            },
        ),
    ]
