# Generated by Django 6.0.6 on 2026-07-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0052_friend_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendnotification',
            name='kind',
            field=models.CharField(choices=[('friend_request', 'Friend request'), ('friend_accepted', 'Friend accepted'), ('friend_at_pub', 'Friend at pub'), ('friend_rsvp', 'Friend RSVP'), ('friend_cheers', 'Friend cheers'), ('friend_plan', 'Friend plan')], db_index=True, max_length=32),
        ),
    ]
