# Generated by Django 6.0.6 on 2026-07-03 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0054_account_search_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendPubActivityRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_friend_pub_activities', to='pubs.account')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_recipients', to='pubs.friendpubactivity')),
            ],
            options={
                'verbose_name': 'Friend pub activity recipient',
                'verbose_name_plural': 'Friend pub activity recipients',
                'indexes': [models.Index(fields=['activity', 'account'], name='pubs_friend_activit_a7fd85_idx'), models.Index(fields=['account', 'activity'], name='pubs_friend_account_2e9ab1_idx')],
                'constraints': [models.UniqueConstraint(fields=('activity', 'account'), name='unique_friend_activity_recipient')],
            },
        ),
    ]
