# Generated by Django 6.0.6 on 2026-07-04 09:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0055_friendpubactivityrecipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('client_id', models.UUIDField(help_text='Client-generated idempotency key.')),
                ('beer_name', models.TextField(help_text='Beer name (1..120 chars, enforced by serializer).')),
                ('brewery_name', models.TextField(blank=True, default='')),
                ('beer_style', models.TextField(blank=True, default='')),
                ('abv', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('pub_cache_key', models.CharField(blank=True, db_index=True, default='', max_length=12)),
                ('pub_name', models.TextField(blank=True, default='')),
                ('pub_city', models.TextField(blank=True, default='')),
                ('visit_client_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('friends', 'Friends')], db_index=True, default='private', max_length=16)),
                ('beer_key', models.CharField(db_index=True, max_length=64)),
                ('brewery_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('checked_in_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_checkins', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Beer check-in',
                'verbose_name_plural': 'Beer check-ins',
                'ordering': ['-checked_in_at'],
            },
        ),
        migrations.CreateModel(
            name='BeerCheckInReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('cheers', 'Cheers')], default='cheers', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_checkin_reactions', to='pubs.account')),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='pubs.beercheckin')),
            ],
            options={
                'verbose_name': 'Beer check-in reaction',
                'verbose_name_plural': 'Beer check-in reactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='beercheckin',
            index=models.Index(fields=['account', 'checked_in_at'], name='pubs_beerch_account_07cafb_idx'),
        ),
        migrations.AddIndex(
            model_name='beercheckin',
            index=models.Index(fields=['visibility', 'checked_in_at'], name='pubs_beerch_visibil_2b0e59_idx'),
        ),
        migrations.AddIndex(
            model_name='beercheckin',
            index=models.Index(fields=['beer_key', 'brewery_key', 'checked_in_at'], name='pubs_beerch_beer_ke_ee8522_idx'),
        ),
        migrations.AddConstraint(
            model_name='beercheckin',
            constraint=models.UniqueConstraint(fields=('account', 'client_id'), name='unique_beer_checkin_per_account_client_id'),
        ),
        migrations.AddIndex(
            model_name='beercheckinreaction',
            index=models.Index(fields=['checkin', 'kind'], name='pubs_beerch_checkin_f1e259_idx'),
        ),
        migrations.AddConstraint(
            model_name='beercheckinreaction',
            constraint=models.UniqueConstraint(fields=('checkin', 'account'), name='unique_beer_checkin_reaction_per_account'),
        ),
    ]
