# Generated by Django 6.0.6 on 2026-07-04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pubs", "0056_beercheckin_beercheckinreaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beercheckin",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name="beercheckin",
            index=models.Index(
                fields=["account", "beer_key", "brewery_key", "checked_in_at"],
                name="pubs_beer_memory_idx",
            ),
        ),
    ]
