# Generated by Django 6.0.6 on 2026-07-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0062_release_note_1_3_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinklog',
            name='drink_type',
            field=models.CharField(choices=[('beer', 'Beer'), ('soft_drink', 'Soft drink'), ('shot', 'Shot')], db_index=True, default='beer', help_text='Drink category. Defaults to beer for released clients and existing rows.', max_length=16),
        ),
    ]
