# Generated by Django 6.0.6 on 2026-07-10 09:22

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import pubs.models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0063_drinklog_drink_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('period_start', models.DateTimeField(unique=True)),
                ('period_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=16)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Photo contest',
                'verbose_name_plural': 'Photo contests',
                'ordering': ['-period_start'],
            },
        ),
        migrations.AddField(
            model_name='accountusagestats',
            name='photo_contest_wins_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contentreport',
            name='reason',
            field=models.CharField(choices=[('inappropriate_nickname', 'Inappropriate nickname'), ('inappropriate_avatar', 'Inappropriate avatar'), ('inappropriate_photo', 'Inappropriate photo'), ('impersonation', 'Impersonation'), ('spam', 'Spam'), ('other', 'Other')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='BeerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('client_id', models.UUIDField(help_text='Client-generated idempotency key.')),
                ('image', models.ImageField(upload_to=pubs.models.beer_photo_path)),
                ('caption', models.CharField(blank=True, default='', max_length=280)),
                ('pub_cache_key', models.CharField(blank=True, db_index=True, default='', max_length=12)),
                ('pub_name', models.TextField(blank=True, default='')),
                ('pub_city', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('friends', 'Friends')], db_index=True, default='friends', max_length=16)),
                ('taken_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Client-provided capture time; defaults to upload time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_photos', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Beer photo',
                'verbose_name_plural': 'Beer photos',
                'ordering': ['-taken_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoContestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('final_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('final_votes', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_contest_entries', to='pubs.account')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='pubs.photocontest')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_entries', to='pubs.beerphoto')),
            ],
            options={
                'verbose_name': 'Photo contest entry',
                'verbose_name_plural': 'Photo contest entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoContestVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='pubs.photocontest')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='pubs.photocontestentry')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_contest_votes', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Photo contest vote',
                'verbose_name_plural': 'Photo contest votes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='beerphoto',
            index=models.Index(fields=['account', '-taken_at'], name='pubs_beerph_account_92c61c_idx'),
        ),
        migrations.AddConstraint(
            model_name='beerphoto',
            constraint=models.UniqueConstraint(fields=('account', 'client_id'), name='unique_beer_photo_per_account_client_id'),
        ),
        migrations.AddIndex(
            model_name='photocontestentry',
            index=models.Index(fields=['contest', 'created_at'], name='pubs_photoc_contest_f02f9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='photocontestentry',
            constraint=models.UniqueConstraint(fields=('contest', 'account'), name='unique_photo_contest_entry_per_account'),
        ),
        migrations.AddConstraint(
            model_name='photocontestentry',
            constraint=models.UniqueConstraint(fields=('contest', 'photo'), name='unique_photo_contest_entry_per_photo'),
        ),
        migrations.AddIndex(
            model_name='photocontestvote',
            index=models.Index(fields=['entry'], name='pubs_photoc_entry_i_c7299b_idx'),
        ),
        migrations.AddConstraint(
            model_name='photocontestvote',
            constraint=models.UniqueConstraint(fields=('contest', 'voter'), name='unique_photo_contest_vote_per_voter'),
        ),
    ]
