# Generated by Django 6.0.6 on 2026-07-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0064_photocontest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientevent',
            name='event',
            field=models.CharField(choices=[('app_open', 'App opened'), ('app_foreground', 'App foregrounded'), ('walking_distance', 'Walking distance'), ('counter_tab_opened', 'Counter tab opened'), ('counter_session_started', 'Counter session started'), ('counter_session_closed', 'Counter session closed'), ('counter_session_resumed', 'Counter session resumed'), ('drink_added', 'Drink added'), ('drink_removed', 'Drink removed'), ('drink_synced', 'Drink synced'), ('drink_sync_failed', 'Drink sync failed'), ('rating_synced', 'Rating synced'), ('rating_sync_failed', 'Rating sync failed'), ('visit_synced', 'Visit synced'), ('visit_sync_failed', 'Visit sync failed'), ('beer_form_opened', 'Beer form opened'), ('beer_form_scan_opened', 'Beer form scan opened'), ('beer_price_added', 'Beer price added'), ('counter_returned_same_day', 'Counter returned same day'), ('counter_returned_later', 'Counter returned later'), ('console_warn', 'Console warning'), ('console_error', 'Console error'), ('unhandled_error', 'Unhandled error'), ('api_failure', 'API failure'), ('amenity_voted', 'Amenity voted'), ('amenity_vote_synced', 'Amenity vote synced'), ('amenity_vote_failed', 'Amenity vote sync failed'), ('leaderboards_opened', 'Leaderboards opened')], db_index=True, max_length=64),
        ),
    ]
