# Generated by Django 6.0.6 on 2026-07-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0072_externalapidailyusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddedpub',
            name='google_place_id',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='useraddedpub',
            name='location_source',
            field=models.CharField(choices=[('user_pin', 'User pin'), ('google_geocode', 'Google geocode')], default='user_pin', help_text='Provenance of the stored coordinates.', max_length=16),
        ),
        migrations.AddField(
            model_name='useraddedpub',
            name='location_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
