# Generated by Django 6.0.6 on 2026-07-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0073_useraddedpub_google_place_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinklog',
            name='drink_type',
            field=models.CharField(choices=[('beer', 'Beer'), ('soft_drink', 'Soft drink'), ('shot', 'Shot'), ('wine', 'Wine')], db_index=True, default='beer', help_text='Drink category. Defaults to beer for released clients and existing rows.', max_length=16),
        ),
    ]
