# Generated by Django 6.0.6 on 2026-07-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0074_alter_drinklog_drink_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='excluded_from_leaderboards',
            field=models.BooleanField(default=False, help_text='Manually exclude this account from global leaderboard scores and listings.'),
        ),
        migrations.AddField(
            model_name='drinklog',
            name='is_suspect',
            field=models.BooleanField(default=False, help_text='Whether this row is excluded from public aggregates by abuse controls.'),
        ),
        migrations.AddField(
            model_name='drinklog',
            name='suspect_reason',
            field=models.CharField(blank=True, default='', help_text='Abuse flag reason: daily_cap, burst, backdated, or manual.', max_length=32),
        ),
    ]
