# Generated by Django 6.0.6 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pubs", "0075_drink_log_abuse_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="drinklog",
            name="place_context",
            field=models.CharField(
                choices=[
                    ("pub", "Pub"),
                    ("private", "Private"),
                    ("outdoors", "Outdoors"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="pub",
                help_text="Where the drink was consumed. Defaults to pub for released clients.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="drinklog",
            name="serving_type",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("draft", "Draft"),
                    ("bottle", "Bottle"),
                    ("can", "Can"),
                    ("plastic_bottle", "Plastic bottle"),
                    ("other", "Other"),
                ],
                default="unknown",
                help_text="How the drink was served; unknown when the client did not provide it.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="drinklog",
            name="cache_key",
            field=models.CharField(
                db_index=True,
                help_text="Geohash-8 of pub (lat, lng), or null outside a pub.",
                max_length=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="drinklog",
            name="lat",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="drinklog",
            name="lng",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="drinklog",
            name="name",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Pub name as the client saw it, or empty outside a pub.",
            ),
        ),
        migrations.AlterField(
            model_name="drinklog",
            name="price_czk",
            field=models.PositiveSmallIntegerField(
                help_text="Price paid in CZK (1..1000), or null when unknown outside a pub.",
                null=True,
            ),
        ),
    ]
