# Generated by Django 6.0.6 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):
    """Store Pivař XP and support hot per-account award existence checks.

    ``(account, drank_at)`` already exists. The added composites cover the
    account-scoped pub, recognized-brand and outside-context lifetime checks;
    PubVisit needs the matching account+geohash lookup for NEW_PUB.
    """

    dependencies = [
        ("pubs", "0076_drinklog_place_context_serving_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountusagestats",
            name="pivar_xp",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name="drinklog",
            index=models.Index(
                fields=["account", "cache_key"],
                name="pubs_drink_account_pub_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="drinklog",
            index=models.Index(
                fields=["account", "beer_brand"],
                name="pubs_drink_account_brand_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="drinklog",
            index=models.Index(
                fields=["account", "place_context"],
                name="pubs_drink_account_context_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pubvisit",
            index=models.Index(
                fields=["account", "cache_key"],
                name="pubs_visit_account_pub_idx",
            ),
        ),
    ]
