# Generated by Django 6.0.6 on 2026-07-17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pubs", "0079_alter_clientevent_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="PubPriceIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(
                        db_index=True,
                        help_text="Geohash-8 of (lat, lng) — matches PubCommunityData.cache_key.",
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.TextField(help_text="Pub name used as the collision guard on reads."),
                ),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("city", models.TextField(blank=True, default="")),
                ("external_id", models.TextField(blank=True, default="")),
                (
                    "price_czk",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ]
                    ),
                ),
                (
                    "volume_ml",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text=(
                            "Unknown volume is stored as null and presented as the Czech "
                            "500 ml default."
                        ),
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("observed_at", models.DateTimeField(db_index=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("community", "Community menu"),
                            ("drink", "Drink log"),
                            ("external", "External menu"),
                        ],
                        max_length=16,
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pub Price Index",
                "verbose_name_plural": "Pub Price Indexes",
                "ordering": ["-observed_at"],
                "indexes": [
                    models.Index(
                        fields=["cache_key", "active"],
                        name="pubs_pubpri_cache_k_ed9141_idx",
                    ),
                    models.Index(
                        fields=["active", "lat", "lng"],
                        name="pubs_pubpri_active_3bdf4b_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("price_czk__gte", 1), ("price_czk__lte", 1000)),
                        name="pub_price_index_valid_price",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("volume_ml__isnull", True), ("volume_ml__gte", 1), _connector="OR"
                        ),
                        name="pub_price_index_valid_volume",
                    ),
                ],
            },
        ),
    ]
