# Generated by Django 6.0.6 on 2026-07-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0080_pub_price_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubGooglePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=12)),
                ('name_key', models.CharField(max_length=255)),
                ('google_place_id', models.CharField(max_length=256)),
                ('matched_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pub Google Place',
                'verbose_name_plural': 'Pub Google Places',
                'constraints': [models.UniqueConstraint(fields=('cache_key', 'name_key'), name='unique_pub_google_place_identity')],
            },
        ),
    ]
