# Generated by Django 6.0.6 on 2026-07-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pubs", "0081_pubgoogleplace"),
    ]

    operations = [
        migrations.AddField(
            model_name="beercheckin",
            name="beer_product",
            field=models.ForeignKey(
                blank=True,
                help_text="Matched canonical beer product used by diary statistics.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkins",
                to="pubs.beerproduct",
            ),
        ),
        migrations.AlterField(
            model_name="beercheckin",
            name="beer_key",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="beercheckin",
            name="brewery_key",
            field=models.CharField(blank=True, db_index=True, default="", max_length=80),
        ),
        migrations.CreateModel(
            name="BeerProductMergeAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_product_id", models.PositiveBigIntegerField()),
                ("source_key", models.SlugField(max_length=100, unique=True)),
                ("source_name", models.CharField(max_length=160)),
                ("target_product_id", models.PositiveBigIntegerField()),
                ("target_key", models.SlugField(db_index=True, max_length=100)),
                ("target_name", models.CharField(max_length=160)),
                ("actor", models.CharField(blank=True, default="", max_length=160)),
                ("rewired", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Beer Product Merge Audit",
                "verbose_name_plural": "Beer Product Merge Audits",
                "ordering": ["-created_at"],
            },
        ),
    ]
