# Generated by Django 6.0.6 on 2026-07-19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pubs", "0083_party_evenings"),
    ]

    operations = [
        migrations.AddField(
            model_name="pubdirectory",
            name="discovery_kind",
            field=models.CharField(
                choices=[
                    ("pub", "Pub"),
                    ("seasonal_stand", "Seasonal stand"),
                    ("campsite", "Campsite"),
                    ("sports_venue", "Sports venue"),
                ],
                db_index=True,
                default="pub",
                help_text="Primary pub or one of the reviewed opt-in discovery categories.",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="pubdirectory",
            name="has_beer_signal",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Reviewed source has an explicit draft-beer, beer, bar, or pub signal.",
            ),
        ),
    ]
