# Generated by Django 6.0.6 on 2026-07-21 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0082_release_note_1_4_1'),
        ('pubs', '0086_community_events'),
    ]

    operations = [
    ]
