# Generated by Django 6.0.6 on 2026-07-22

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pubs", "0087_merge_0082_release_note_1_4_1_0086_community_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishedNight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        help_text="Client-generated idempotency key.",
                        max_length=128,
                    ),
                ),
                ("drinking_day", models.DateField()),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField()),
                ("beer_count", models.PositiveSmallIntegerField()),
                ("wine_count", models.PositiveSmallIntegerField()),
                ("soft_drink_count", models.PositiveSmallIntegerField()),
                ("shot_count", models.PositiveSmallIntegerField()),
                ("pub_names", models.JSONField(blank=True, default=list)),
                ("city", models.CharField(blank=True, default="", max_length=120)),
                ("duration_minutes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("friends", "Friends"), ("public", "Public")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_at",
                    models.DateTimeField(
                        help_text="Client timestamp used as the last-write-wins conflict key."
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_nights",
                        to="pubs.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Published night",
                "verbose_name_plural": "Published nights",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["visibility", "-created_at"],
                        name="pubs_night_vis_created_idx",
                    ),
                    models.Index(
                        fields=["account", "drinking_day"],
                        name="pubs_night_account_day_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "client_id"),
                        name="unique_published_night_per_account_client_id",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NightRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="night_rounds",
                        to="pubs.account",
                    ),
                ),
                (
                    "night",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="pubs.publishednight",
                    ),
                ),
            ],
            options={
                "verbose_name": "Night round",
                "verbose_name_plural": "Night rounds",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("night", "account"),
                        name="unique_night_round_per_account",
                    )
                ],
            },
        ),
    ]
