# Generated by Django 6.0.6 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pubs", "0088_published_nights"),
    ]

    operations = [
        migrations.AddField(
            model_name="pubcommunitydata",
            name="beer_menu_rotates",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Whether the pub intentionally changes its taps instead of keeping a "
                    "regular beer menu. The stored beers remain the latest confirmed snapshot."
                ),
            ),
        ),
    ]
