# Generated by Django 6.0.6 on 2026-07-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pubs", "0089_pubcommunitydata_beer_menu_rotates"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="share_drinks_with_parta",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Whether accepted friends can see my live pub presence "
                    "and automatic drink feed."
                ),
            ),
        ),
    ]
