# Generated by Django 6.0.6 on 2026-07-29 13:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0090_account_share_drinks_with_parta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalPub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cache_key', models.CharField(db_index=True, max_length=12)),
                ('name', models.CharField(max_length=255)),
                ('name_key', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('city', models.CharField(blank=True, default='', max_length=128)),
                ('country', models.CharField(blank=True, db_index=True, default='', max_length=2)),
                ('external_id', models.CharField(blank=True, default='', max_length=256)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Canonical Pub',
                'verbose_name_plural': 'Canonical Pubs',
                'constraints': [models.UniqueConstraint(fields=('cache_key', 'name_key'), name='unique_canonical_pub_identity')],
            },
        ),
        migrations.CreateModel(
            name='PubMergeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_cache_key', models.CharField(max_length=12)),
                ('source_name', models.CharField(max_length=255)),
                ('target_cache_key', models.CharField(max_length=12)),
                ('target_name', models.CharField(max_length=255)),
                ('actor', models.CharField(max_length=128)),
                ('reason', models.TextField()),
                ('affected_rows', models.JSONField(default=dict)),
                ('deactivated_directory_ids', models.JSONField(default=list)),
                ('deactivated_user_added_ids', models.JSONField(default=list)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('reverted_by', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canonical_pub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merge_audits', to='pubs.canonicalpub')),
            ],
            options={
                'verbose_name': 'Pub Merge Audit',
                'verbose_name_plural': 'Pub Merge Audits',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PubAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=12)),
                ('name', models.CharField(max_length=255)),
                ('name_key', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('is_primary', models.BooleanField(default=False)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_pub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='pubs.canonicalpub')),
            ],
            options={
                'verbose_name': 'Pub Alias',
                'verbose_name_plural': 'Pub Aliases',
                'indexes': [models.Index(fields=['cache_key', 'active'], name='pubalias_cache_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('cache_key', 'name_key'), name='unique_pub_alias_identity'), models.UniqueConstraint(condition=models.Q(('active', True), ('is_primary', True)), fields=('canonical_pub',), name='unique_active_primary_pub_alias')],
            },
        ),
    ]
