# Generated by Django 6.0.6 on 2026-08-03 17:21

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0093_alter_clientevent_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('client_id', models.UUIDField(help_text='Client-generated idempotency key for offline retries.')),
                ('catalog_key', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=80)),
                ('scoring', models.CharField(choices=[('points', 'Points'), ('drinks', 'Drinks')], default='points', max_length=8)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('evening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='pubs.partyevening')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_party_games', to='pubs.account')),
            ],
            options={
                'ordering': ['started_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PartyGameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField(help_text='Idempotency key; a retried event must not double-count.')),
                ('kind', models.CharField(choices=[('score', 'Score'), ('finish', 'Finish')], max_length=8)),
                ('delta', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_game_events', to='pubs.account')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pubs.partygame')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_game_scores', to='pubs.account')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='partygame',
            index=models.Index(fields=['evening', 'started_at'], name='party_game_evening_idx'),
        ),
        migrations.AddConstraint(
            model_name='partygame',
            constraint=models.UniqueConstraint(fields=('evening', 'client_id'), name='unique_party_game_client'),
        ),
        migrations.AddIndex(
            model_name='partygameevent',
            index=models.Index(fields=['game', 'id'], name='party_game_event_cursor_idx'),
        ),
        migrations.AddConstraint(
            model_name='partygameevent',
            constraint=models.UniqueConstraint(fields=('game', 'client_id'), name='unique_party_game_event_client'),
        ),
    ]
