# Generated by Django 6.0.6 on 2026-07-30 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pubs", "0093_alter_clientevent_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfflineMutationTombstone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        choices=[("drink", "Drink"), ("pub_visit", "Pub visit")],
                        max_length=16,
                    ),
                ),
                ("client_id", models.UUIDField()),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Offline mutation tombstone",
                "verbose_name_plural": "Offline mutation tombstones",
            },
        ),
        migrations.AddField(
            model_name="drinklog",
            name="evening_client_id",
            field=models.UUIDField(
                blank=True,
                help_text=(
                    "Optional client-generated evening UUID (PubVisit.client_id). "
                    "Released clients omit it."
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pubvisit",
            name="closed_at",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "Explicit client-confirmed Dopito time. Null for active visits and "
                    "released clients that only send ended_at."
                ),
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="drinklog",
            index=models.Index(
                fields=["account", "evening_client_id", "drank_at"],
                name="pubs_drink_evening_idx",
            ),
        ),
        migrations.AddField(
            model_name="offlinemutationtombstone",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offline_mutation_tombstones",
                to="pubs.account",
            ),
        ),
        migrations.AddConstraint(
            model_name="offlinemutationtombstone",
            constraint=models.UniqueConstraint(
                fields=("account", "resource", "client_id"),
                name="unique_offline_tombstone",
            ),
        ),
    ]
