# Generated by Django 6.0.6 on 2026-08-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0094_partygame_partygameevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partygameevent',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='partygameevent',
            name='kind',
            field=models.CharField(choices=[('score', 'Score'), ('finish', 'Finish'), ('answer', 'Answer')], max_length=8),
        ),
    ]
