# Generated by Django 6.0.6 on 2026-08-05 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0095_partygameevent_payload_alter_partygameevent_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinklog',
            name='party_evening',
            field=models.ForeignKey(blank=True, help_text='The shared evening this drink was logged during, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_drinks', to='pubs.partyevening'),
        ),
        migrations.AddIndex(
            model_name='drinklog',
            index=models.Index(fields=['party_evening', 'drank_at'], name='pubs_drink_party_idx'),
        ),
    ]
