# Generated by Django 6.0.6 on 2026-08-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pubs", "0096_drinklog_party_evening_drinklog_pubs_drink_party_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="beerphoto",
            name="party_evening",
            field=models.ForeignKey(
                blank=True,
                help_text="The shared evening this photo was taken during, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="party_photos",
                to="pubs.partyevening",
            ),
        ),
        migrations.AddField(
            model_name="pubvisit",
            name="party_evening",
            field=models.ForeignKey(
                blank=True,
                help_text="The shared evening this visit was part of, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="party_visits",
                to="pubs.partyevening",
            ),
        ),
        migrations.AddIndex(
            model_name="beerphoto",
            index=models.Index(
                fields=["party_evening", "taken_at"],
                name="pubs_photo_party_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pubvisit",
            index=models.Index(
                fields=["party_evening", "started_at"],
                name="pubs_visit_party_time_idx",
            ),
        ),
    ]
