# Generated by Django 6.0.6 on 2026-08-07 11:32

from datetime import datetime
from zoneinfo import ZoneInfo

from django.db import migrations, models

LAUNCH_SLUGS = ("pet-hospod-pet-pribehu", "tri-fotky-od-stolu")


def seed_launch_challenges(apps, schema_editor):
    Challenge = apps.get_model("pubs", "Challenge")
    prague = ZoneInfo("Europe/Prague")
    window_start = datetime(2026, 8, 1, tzinfo=prague)
    window_end = datetime(2026, 9, 1, tzinfo=prague)
    Challenge.objects.bulk_create(
        [
            Challenge(
                slug=LAUNCH_SLUGS[0],
                title="Pět hospod, pět příběhů",
                glyph_key="places",
                metric_rule="distinct_pubs",
                target=5,
                unit="hospod",
                blurb=(
                    "Oběhni pět různých hospod. Štamgastovská jistota se počítá jen jednou."
                ),
                reward="Odznak Hospodský poutník",
                rules=[
                    "Počítá se každá různá hospoda navštívená během srpna.",
                    "Stačí potvrzená návštěva nebo zápis od stolu.",
                    "Jedna hospoda má jeden zářez, i když se vrátíš.",
                ],
                window_start=window_start,
                window_end=window_end,
                active=True,
            ),
            Challenge(
                slug=LAUNCH_SLUGS[1],
                title="Tři fotky od stolu",
                glyph_key="rhythm",
                metric_rule="photo_count",
                target=3,
                unit="fotek",
                blurb=(
                    "Tři momentky, co budou zítra dávat smysl. Nebo aspoň připomenou, "
                    "kde jsi seděl."
                ),
                reward="Odznak Stolní kronikář",
                rules=[
                    "Počítá se fotka přidaná do pivního deníčku během srpna.",
                    "Jedna fotka je jeden zářez.",
                    "Soukromá fotka zůstává soukromá; parta vidí jen souhrnný postup.",
                ],
                window_start=window_start,
                window_end=window_end,
                active=True,
            ),
        ]
    )


def remove_launch_challenges(apps, schema_editor):
    Challenge = apps.get_model("pubs", "Challenge")
    Challenge.objects.filter(slug__in=LAUNCH_SLUGS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0096_drinklog_party_evening_drinklog_pubs_drink_party_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('glyph_key', models.CharField(choices=[('places', 'Places'), ('rhythm', 'Rhythm'), ('taste', 'Taste')], max_length=16)),
                ('metric_rule', models.CharField(choices=[('beer_count', 'Beer count'), ('distinct_pubs', 'Distinct pubs'), ('photo_count', 'Photo count')], max_length=24)),
                ('target', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=40)),
                ('blurb', models.TextField(blank=True, default='')),
                ('reward', models.CharField(blank=True, default='', max_length=120)),
                ('rules', models.JSONField(blank=True, default=list)),
                ('window_start', models.DateTimeField(db_index=True)),
                ('window_end', models.DateTimeField(db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['window_end', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('target__gt', 0)), name='challenge_target_positive'), models.CheckConstraint(condition=models.Q(('window_end__gt', models.F('window_start'))), name='challenge_window_order')],
            },
        ),
        migrations.RunPython(seed_launch_challenges, remove_launch_challenges),
    ]
