# Generated by Django 6.0.6 on 2026-08-06 20:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pubs", "0098_unique_published_night_drinking_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityEventTeam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("client_id", models.UUIDField()),
                ("name", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_community_event_teams",
                        to="pubs.account",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="pubs.communityevent",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="CommunityEventTeamMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slot", models.PositiveSmallIntegerField()),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_event_team_memberships",
                        to="pubs.account",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to="pubs.communityevent",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="pubs.communityeventteam",
                    ),
                ),
            ],
            options={
                "ordering": ["slot", "joined_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="communityeventteam",
            index=models.Index(fields=["event", "created_at"], name="community_team_event_lookup"),
        ),
        migrations.AddConstraint(
            model_name="communityeventteam",
            constraint=models.UniqueConstraint(
                fields=("event", "client_id"), name="unique_event_team_client"
            ),
        ),
        migrations.AddConstraint(
            model_name="communityeventteammembership",
            constraint=models.UniqueConstraint(
                fields=("event", "account"), name="unique_event_team_account"
            ),
        ),
        migrations.AddConstraint(
            model_name="communityeventteammembership",
            constraint=models.UniqueConstraint(
                fields=("team", "account"), name="unique_team_account"
            ),
        ),
        migrations.AddConstraint(
            model_name="communityeventteammembership",
            constraint=models.UniqueConstraint(
                fields=("team", "slot"), name="unique_event_team_slot"
            ),
        ),
        migrations.AddConstraint(
            model_name="communityeventteammembership",
            constraint=models.CheckConstraint(
                condition=models.Q(("slot__gte", 1), ("slot__lte", 4)), name="event_team_slot_1_4"
            ),
        ),
    ]
