# Generated by Django 6.0.6 on 2026-08-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0113_alter_partygameevent_kind'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='publishednight',
            index=models.Index(fields=['account', '-created_at'], name='pubs_publis_account_5eef71_idx'),
        ),
        migrations.AddIndex(
            model_name='pubvisit',
            index=models.Index(fields=['account', 'ended_at'], name='pubs_pubvis_account_fcd1c0_idx'),
        ),
    ]
