# Generated by Django 6.0.6 on 2026-08-14 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0114_publishednight_pubs_publis_account_5eef71_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to='pubs.account')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Follow',
                'verbose_name_plural': 'Follows',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['follower', '-created_at'], name='pubs_follow_follower_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('follower', 'target'), name='unique_follow_pair'), models.CheckConstraint(condition=models.Q(('follower', models.F('target')), _negated=True), name='follow_no_self')],
            },
        ),
    ]
