# Generated by Django 6.0.8 on 2026-08-21 14:38

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0115_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRateLimitBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=64)),
                ('identity_hash', models.CharField(max_length=64)),
                ('window_started_at', models.DateTimeField()),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['window_started_at'], name='api_rate_window_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'identity_hash', 'window_started_at'), name='unique_api_rate_limit_bucket')],
            },
        ),
        migrations.CreateModel(
            name='AccountExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivered', 'Delivered')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='pubs.account')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='account_export_ready_idx'), models.Index(fields=['lease_expires_at'], name='account_export_lease_idx')],
            },
        ),
    ]
