# Generated by Django 6.0.8 on 2026-08-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pubs", "0116_release_backend_p3"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountexportjob",
            name="failed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accountexportjob",
            name="lease_token",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="accountexportjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="accountexportjob",
            index=models.Index(
                fields=["status", "failed_at"], name="account_export_failed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pubreport",
            index=models.Index(
                fields=["active", "lat", "lng"], name="pub_report_geo_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pubreport",
            index=models.Index(
                fields=["cache_key", "active", "account"],
                name="pub_report_quorum_idx",
            ),
        ),
    ]
