# Generated by Django 6.0.8 on 2026-08-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0096_release_note_1_5_1'),
        ('pubs', '0119_anonymize_shared_ownership'),
    ]

    operations = [
    ]
