# Generated by Django 6.0.8 on 2026-08-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0120_merge_20260822_1543'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accountdeletionoperation',
            index=models.Index(fields=['completed_at'], name='accdelop_completed_idx'),
        ),
        migrations.AddIndex(
            model_name='accountmergeoperation',
            index=models.Index(fields=['completed_at'], name='accmergeop_completed_idx'),
        ),
        migrations.AddIndex(
            model_name='contentreport',
            index=models.Index(fields=['created_at'], name='contentrep_created_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackreport',
            index=models.Index(fields=['created_at'], name='feedbackrep_created_idx'),
        ),
    ]
