# Generated by Django 6.0.8 on 2026-08-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0121_retention_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ugc_terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When the account accepted the community-content terms version recorded in ugc_terms_version; null means never accepted.', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='ugc_terms_version',
            field=models.CharField(blank=True, default='', help_text='Version of the community-content terms this account accepted; empty means no acceptance recorded.', max_length=32),
        ),
    ]
