# Generated by Django 6.0.8 on 2026-08-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0122_ugc_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerphotofiledeletion',
            name='client_id',
            field=models.UUIDField(blank=True, help_text='Client identity of the deleted beer photo; null for avatars and feedback attachments.', null=True),
        ),
        migrations.AlterField(
            model_name='beerphotofiledeletion',
            name='file_kind',
            field=models.CharField(choices=[('beer_photo', 'Beer photo'), ('avatar', 'Avatar'), ('feedback', 'Feedback attachment')], default='beer_photo', help_text='Selects the Django storage field used for physical cleanup.', max_length=16),
        ),
    ]
