# Generated by Django 6.0.8 on 2026-08-23 18:39

import django.db.models.deletion
from django.db import migrations, models


def reserve_existing_party_evening_codes(apps, schema_editor):
    PartyEvening = apps.get_model('pubs', 'PartyEvening')
    PartyEveningCode = apps.get_model('pubs', 'PartyEveningCode')
    PartyEveningCode.objects.bulk_create(
        [
            PartyEveningCode(join_code=join_code, evening_id=evening_id)
            for evening_id, join_code in PartyEvening.objects.values_list(
                'pk', 'join_code'
            ).iterator()
        ],
        batch_size=1_000,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0125_release_note_3_0_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyEveningCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_code', models.CharField(max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='pubs.partyevening')),
            ],
        ),
        migrations.RunPython(
            reserve_existing_party_evening_codes,
            migrations.RunPython.noop,
        ),
    ]
