# Generated by Django 6.0.8 on 2026-08-23 19:34

import django.db.models.deletion
from django.db import migrations, models


def freeze_existing_game_seeds(apps, schema_editor):
    PartyGame = apps.get_model("pubs", "PartyGame")
    pending = []
    for game in PartyGame.objects.select_related("evening").iterator(chunk_size=1_000):
        seed = 2_166_136_261
        identity = f"{game.evening.join_code.upper()}:{game.catalog_key}"
        for byte in identity.encode("ascii"):
            seed = ((seed ^ byte) * 16_777_619) & 0xFFFF_FFFF
        game.seed = (seed & 0x7FFF_FFFF) or 1
        pending.append(game)
        if len(pending) == 1_000:
            PartyGame.objects.bulk_update(pending, ["seed"], batch_size=1_000)
            pending.clear()
    if pending:
        PartyGame.objects.bulk_update(pending, ["seed"], batch_size=1_000)


class Migration(migrations.Migration):

    dependencies = [
        ("pubs", "0126_party_evening_alias"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountIdentityAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_id", models.UUIDField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_aliases",
                        to="pubs.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartyGameAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_id", models.UUIDField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="pubs.partygame",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="partygame",
            name="seed",
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.RunPython(
            freeze_existing_game_seeds,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="partygame",
            name="seed",
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
