# Generated by Django 6.0.8 on 2026-08-23

from django.db import migrations, models


def redact_existing_game_payloads(apps, schema_editor):
    """Pre-3.0 rows cannot prove that no already-purged player is named."""
    PartyGame = apps.get_model("pubs", "PartyGame")
    PartyGameEvent = apps.get_model("pubs", "PartyGameEvent")
    PartyGame.objects.all().update(payloads_redacted=True)
    PartyGameEvent.objects.exclude(payload={}).update(payload={})


class Migration(migrations.Migration):

    dependencies = [
        ("pubs", "0127_partygame_seed_accountidentityalias"),
    ]

    operations = [
        migrations.AddField(
            model_name="partygame",
            name="payloads_redacted",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            redact_existing_game_payloads,
            migrations.RunPython.noop,
        ),
    ]
