# Generated by Django 6.0.8 on 2026-08-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0132_release_note_2_0_0_games_later'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='locale',
            field=models.CharField(blank=True, default='', help_text="Last known app language ('cs' or 'en'). Empty means unknown, which renders Czech. Used out of request context (push, e-mail, cron).", max_length=8),
        ),
        migrations.AddField(
            model_name='amenitykind',
            name='label_en',
            field=models.CharField(blank=True, default='', help_text="English display label, e.g. 'Card payment'. Falls back to label when blank.", max_length=80),
        ),
        migrations.AddField(
            model_name='amenitykind',
            name='short_label_en',
            field=models.CharField(blank=True, default='', help_text='Optional compact English chip label.', max_length=40),
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='locale',
            field=models.CharField(blank=True, default='', help_text="App language of this device ('cs' or 'en'). Empty means unknown, which renders Czech. Released app versions never send it.", max_length=8),
        ),
        migrations.AddField(
            model_name='releasenote',
            name='title_en',
            field=models.CharField(blank=True, default='', help_text='English headline. Blank means this note has no English copy and the app hides the popup for English users.', max_length=120),
        ),
        migrations.AddField(
            model_name='releasenoteitem',
            name='text_en',
            field=models.CharField(blank=True, default='', help_text='The same change in English. Blank means no English copy for this bullet.', max_length=280),
        ),
    ]
