# Generated by Django 6.0.8 on 2026-09-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0135_release_note_2_0_0_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='share_spend_with_parta',
            field=models.BooleanField(default=False, help_text='Whether a Souboj with an accepted friend may compare my total spend.'),
        ),
    ]
