# Generated by Django 6.1.1 on 2026-09-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0138_release_note_2_1_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushdevice',
            name='client_revision',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
