# Generated by Django 6.1.1 on 2026-09-18 08:13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0138_release_note_2_1_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Europe/Prague', max_length=64)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='pubs.account')),
            ],
        ),
        migrations.CreateModel(
            name='TourShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField()),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share', to='pubs.tourplan')),
            ],
        ),
        migrations.CreateModel(
            name='TourOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField()),
                ('kind', models.CharField(max_length=8)),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='pubs.tourplan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plan', 'operation_id'), name='tour_operation_identity')],
            },
        ),
        migrations.CreateModel(
            name='TourStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField()),
                ('position', models.PositiveSmallIntegerField()),
                ('pub_id', models.CharField(max_length=256)),
                ('cache_key', models.CharField(blank=True, max_length=32, null=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='pubs.tourplan')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'client_id'), name='tour_stop_identity'), models.UniqueConstraint(fields=('plan', 'position'), name='tour_stop_position'), models.UniqueConstraint(fields=('plan', 'pub_id'), name='tour_stop_pub')],
            },
        ),
    ]
