# Generated by Django 6.1.1 on 2026-09-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0139_order_push_device_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubGeocodingMiss',
            fields=[
                ('address_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
