# Generated by Django 6.1.1 on 2026-09-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0140_cache_pub_geocoding_misses'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddedpub',
            name='location_refresh_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
