# Generated by Django 6.1.1 on 2026-09-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0143_tour_operation_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourstop',
            name='challenge',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
