# Generated by Django 6.1.1 on 2026-09-25 17:29

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0144_tour_stop_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentreport',
            name='reason',
            field=models.CharField(choices=[('inappropriate_nickname', 'Inappropriate nickname'), ('inappropriate_avatar', 'Inappropriate avatar'), ('inappropriate_photo', 'Inappropriate photo'), ('inappropriate_tour', 'Inappropriate tour'), ('impersonation', 'Impersonation'), ('spam', 'Spam'), ('other', 'Other')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='TourPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('hidden', 'Hidden'), ('unpublished', 'Unpublished')], db_index=True, default='active', max_length=12)),
                ('hidden_reason', models.CharField(blank=True, default='', max_length=32)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('plan_revision', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('title', models.CharField(max_length=60)),
                ('city', models.CharField(blank=True, default='', max_length=128)),
                ('start_lat', models.FloatField()),
                ('start_lon', models.FloatField()),
                ('stop_count', models.PositiveSmallIntegerField()),
                ('walk_m', models.PositiveIntegerField()),
                ('has_challenges', models.BooleanField(default=False)),
                ('people_count', models.PositiveIntegerField(default=0)),
                ('rules_accepted_at', models.DateTimeField()),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='pubs.tourplan')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'start_lat', 'start_lon'], name='tour_publication_geo')],
            },
        ),
    ]
