# Generated by Django 6.1.1 on 2026-09-25 18:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0145_tour_publications'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpublication',
            name='count_since',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tourpublication',
            name='people_count_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TourRun',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_tour_runs', to='pubs.account')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='pubs.tourpublication')),
            ],
        ),
        migrations.CreateModel(
            name='TourRunMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_run_memberships', to='pubs.account')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='pubs.tourrun')),
            ],
            options={
                'indexes': [models.Index(fields=['account', 'completed_at'], name='tour_run_member_done')],
                'constraints': [models.UniqueConstraint(fields=('run', 'account'), name='tour_run_member_identity')],
            },
        ),
    ]
