# Generated by Django 6.1.1 on 2026-09-25 21:53

from django.db import migrations, models


def fill_search_text(apps, schema_editor):
    from pubs.tours import publication_search_text

    TourPublication = apps.get_model("pubs", "TourPublication")
    for publication in TourPublication.objects.only("pk", "snapshot").iterator():
        TourPublication.objects.filter(pk=publication.pk).update(search_text=publication_search_text(publication.snapshot))


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0146_tour_runs'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpublication',
            name='search_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(fill_search_text, migrations.RunPython.noop),
    ]
