# Generated by Django 6.1.1 on 2026-09-28 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0148_seed_regional_beer_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubRatingTombstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=12)),
                ('client_updated_at', models.DateTimeField(help_text='Client time of the latest removal; the last-write-wins conflict key.')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pub_rating_tombstones', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Pub Rating Tombstone',
                'verbose_name_plural': 'Pub Rating Tombstones',
                'ordering': ['-client_updated_at'],
                'constraints': [models.UniqueConstraint(fields=('account', 'cache_key'), name='unique_rating_tombstone_per_account_pub')],
            },
        ),
    ]
