# Generated by Django 6.1.1 on 2026-09-28 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0148_seed_regional_beer_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, help_text='Geohash-8 of (lat, lng) — ~38 m precision; matches PubRating.cache_key.', max_length=12)),
                ('name', models.TextField(blank=True, default='', help_text='Pub name as the client saw it.')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('external_id', models.TextField(blank=True, default='', help_text='Client-side provider id, e.g. Mapy.cz item id.')),
                ('client_updated_at', models.DateTimeField(help_text="Client's local updatedAt; the last-write-wins conflict key.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='The user who owns this private favourite.', on_delete=django.db.models.deletion.CASCADE, related_name='pub_favorites', to='pubs.account')),
            ],
            options={
                'verbose_name': 'Pub Favorite',
                'verbose_name_plural': 'Pub Favorites',
                'ordering': ['-client_updated_at'],
                'constraints': [models.UniqueConstraint(fields=('account', 'cache_key'), name='unique_favorite_per_account_pub')],
            },
        ),
    ]
