# Generated by Django 6.1.1 on 2026-09-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0150_pubfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='table_visible_until',
            field=models.DateTimeField(blank=True, help_text="Short explicit opt-in: until then, people sitting in the same pub may see this profile in 'Kdo tu sedí s tebou'. Null = hidden.", null=True),
        ),
    ]
