# Generated by Django 6.1.1 on 2026-09-28 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0150_pubfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendnotification',
            name='kind',
            field=models.CharField(choices=[('friend_request', 'Friend request'), ('friend_accepted', 'Friend accepted'), ('friend_at_pub', 'Friend at pub'), ('friend_rsvp', 'Friend RSVP'), ('friend_cheers', 'Friend cheers'), ('friend_plan', 'Friend plan'), ('friend_tour_invite', 'Friend tour invite')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='TourInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('going', 'Going'), ('declined', 'Declined')], default='invited', max_length=12)),
                ('share_operation_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_invites', to='pubs.account')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='pubs.tourplan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plan', 'invitee'), name='tour_invite_identity')],
            },
        ),
    ]
