# Generated by Django 6.1.1 on 2026-10-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0152_account_table_visible_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubPriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('computed_at', models.DateTimeField()),
                ('data', models.JSONField()),
                ('og_image_cs', models.BinaryField()),
                ('og_image_en', models.BinaryField()),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
    ]
