# Generated by Django 6.1.1 on 2026-10-07 07:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0152_account_table_visible_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=500)),
                ('sha256', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=40)),
                ('etag', models.CharField(blank=True, default='', max_length=255)),
                ('last_modified', models.CharField(blank=True, default='', max_length=64)),
                ('feed_start', models.DateField(blank=True, null=True)),
                ('feed_end', models.DateField(blank=True, null=True)),
                ('window_start', models.DateField()),
                ('window_end', models.DateField()),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransitPatternStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.PositiveIntegerField()),
                ('idx', models.PositiveSmallIntegerField()),
                ('stop_id', models.CharField(max_length=64)),
                ('can_board', models.BooleanField()),
                ('can_alight', models.BooleanField()),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pubs.transitfeed')),
            ],
            options={
                'indexes': [models.Index(fields=['feed', 'stop_id'], name='transit_pattern_stop')],
            },
        ),
        migrations.CreateModel(
            name='TransitServiceDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pubs.transitfeed')),
            ],
            options={
                'indexes': [models.Index(fields=['feed', 'date'], name='transit_service_date')],
            },
        ),
        migrations.CreateModel(
            name='TransitStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pubs.transitfeed')),
            ],
            options={
                'indexes': [models.Index(fields=['feed', 'lat', 'lng'], name='transit_stop_geo')],
                'constraints': [models.UniqueConstraint(fields=('feed', 'stop_id'), name='transit_stop_identity')],
            },
        ),
        migrations.CreateModel(
            name='TransitTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.PositiveIntegerField()),
                ('route_short_name', models.CharField(max_length=32)),
                ('route_type', models.PositiveSmallIntegerField()),
                ('headsign', models.CharField(blank=True, default='', max_length=255)),
                ('service_id', models.CharField(max_length=64)),
                ('departures', models.JSONField()),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pubs.transitfeed')),
            ],
            options={
                'indexes': [models.Index(fields=['feed', 'pattern'], name='transit_trip_pattern')],
            },
        ),
    ]
