# Hand-written: add the beers people actually write on pub menus to the
# catalog, so autocomplete offers them and every write stores one spelling.
#
# The list comes from the production menus and drink names of October 2026
# (names at least 3 people or pubs use), researched against brewery sites and
# Czech beer slang (Radek = Radegast, Staráč = Staropramen, Plznička = Pilsner
# Urquell). Names that could mean two beers stay free text. An exact alias match
# rewrites a typed name to the product name on every write, from every app
# version, so aliases are only spellings of that one beer: never a bare brand
# name, never another degree, never nealko/radler/flavour of a different beer.
#
# Existing menus are rewritten separately by `manage.py clean_beer_menus`.
# Drink logs are not touched here or there.

from django.db import migrations

SOURCE_LABEL = "Curated from Na pivo menus"

# key, name, aliases
BRANDS = [
    ("policka", "Polička", []),
    ("hoegaarden", "Hoegaarden", ["Hoegarden"]),
    ("vinohradsky", "Vinohradský pivovar", []),
    ("samson", "Samson", []),
    ("rampusak", "Rampušák", []),
    ("birgo", "Birgo", []),
    ("guinness", "Guinness", ["Guiness"]),
    ("kutna-hora", "Kutná Hora", []),
    ("hauskrecht", "Hauskrecht", ["Hausknecht"]),
    ("argus", "Argus", []),
    ("lucky-bastard", "Lucky Bastard", []),
    ("raven", "Raven", []),
    ("mordyr", "Mordýř", []),
    ("lomnicke", "Lomnické pivo", ["Lomnické"]),
    ("cvikov", "Cvikov", []),
    ("zlata-labut", "Zlatá labuť", []),
    ("vorkloster", "Vorkloster", []),
    ("bradac", "Bradáč", []),
    ("zvikov", "Zvíkov", []),
    ("turnov", "Turnov", []),
    ("maisels-weisse", "Maisel's Weisse", []),
    ("libertas", "Libertas", []),
    ("hostivar", "Hostivar", []),
    ("falkenstejn", "Falkenštejn", []),
    ("heineken", "Heineken", ["Heineker"]),
    ("corona", "Corona", []),
    ("tri-sestry", "Tři Sestry", []),
    ("elektrarna", "Elektrárna", []),
    ("zewl", "Zewl", []),
    ("beskydsky", "Beskydský pivovárek", ["Beskydské"]),
    ("proud", "Proud", []),
    ("stella-artois", "Stella Artois", ["Stella"]),
    ("karlovacko", "Karlovačko", ["Karlovačka"]),
    ("desperados", "Desperados", ["Desperado"]),
    ("ozujsko", "Ožujsko", []),
    ("skopsko", "Skopsko", []),
    ("cruzcampo", "Cruzcampo", []),
    ("paulaner", "Paulaner", []),
    ("birra-moretti", "Birra Moretti", ["Moretti"]),
    ("mythos", "Mythos", []),
    ("zlaten-dab", "Zlaten Dab", []),
    ("lasko", "Laško", []),
    ("estrella-galicia", "Estrella Galicia", []),
    ("coral", "Coral", []),
    ("messina", "Messina", []),
    ("augustiner", "Augustiner", []),
    ("alhambra", "Alhambra", []),
    ("amstel", "Amstel", []),
    ("kamenice-nad-lipou", "Pivovar Kamenice nad Lipou", []),
    ("konicek", "Koníček", []),
    ("chric", "Chříč", []),
    ("splavek", "Splávek", ["Pivovar Choceň"]),
    ("ohrada", "Ohrada", []),
    ("trautenberk", "Trautenberk", []),
    ("morava", "Pivovárek Morava", []),
    ("slavkov", "Slavkovský pivovar", []),
    ("kbelsky", "Kbelský pivovar", []),
    ("vltavotynsky", "Vltavotýnský pivovar", []),
    ("jindra", "Jindra", []),
    ("zlata-krava", "Zlatá kráva", []),
    ("jarosovsky", "Jarošovský pivovar", []),
    ("plasy", "Knížecí pivovar Plasy", []),
    ("klaster", "Pivovar Klášter", []),
    ("stiegl", "Stiegl", []),
    ("san-miguel", "San Miguel", []),
    ("krombacher", "Krombacher", []),
    ("franziskaner", "Franziskaner", []),
    ("tuborg", "Tuborg", []),
    ("super-bock", "Super Bock", []),
    ("erdinger", "Erdinger", []),
    ("hertog-jan", "Hertog Jan", []),
    ("mahou", "Mahou", []),
    ("spaten", "Spaten", []),
    ("ganter", "Ganter", []),
    ("zywiec", "Żywiec", []),
    ("lech", "Lech", []),
    ("peroni", "Peroni", []),
    ("dreher", "Dreher", []),
    ("borsodi", "Borsodi", []),
    ("soproni", "Soproni", []),
    ("ichnusa", "Ichnusa", []),
    ("fenek", "Fenek", []),
    ("senticky-kvasar", "Sentický Kvasar", []),
    ("gutmann", "Gutmann", ["GUTMMAN"]),
    ("muflon", "Muflon", []),
    ("u-tomana", "U Tomana", []),
    ("pocernak", "Počerňák", []),
    ("bratcice", "Zámecký pivovar Bratčice", []),
    ("efes", "Efes", []),
    ("zajecarsko", "Zaječarsko", []),
    ("niksicko", "Nikšićko", []),
    ("forst", "Forst", []),
    ("bintang", "Bintang", []),
    ("lowenbrau", "Löwenbräu", []),
    ("kilkenny", "Kilkenny", []),
    ("frankies", "Frankies", []),
    ("vildenberg", "Vildenberg", ["Vildenberk"]),
    ("tupadly", "Pivovar Tupadly", []),
    ("dock7", "DOCK7", []),
    ("moravia", "Pivovar Moravia", []),
    ("moucha", "Pivovar Moucha", []),
    ("spojovna", "Spojovna", []),
    ("volt", "Volt", []),
    ("rudohor", "Rudohor", []),
    ("rezek", "Rezek", []),
    ("tisnov", "Tišnovský pivovar", []),
    ("pegas", "Pegas", []),
    ("obora", "Pivovar Obora", []),
    ("madcat", "MadCat", []),
    ("czech-lion", "Czech Lion", []),
    ("cierny-kamen", "Čierny Kameň", []),
    ("maloskalsky", "Maloskalský pivovar", []),
    ("schladminger", "Schladminger Bier", []),
    ("haksna", "HAKSNA Brewery", []),
    ("efi", "EFI Pivovar", []),
    ("andelsky", "Andělský pivovar", []),
    ("valaisanne", "Valaisanne", []),
    ("beamish", "Beamish", []),
]

# brand_key, key, name, aliases. Most used first: the order sets the
# suggestion rank.
PRODUCTS = [
    ("birell", "birell-pomelo-grep", "Birell Pomelo & Grep", ["Birell Pomelo a Grep", "Radegast Birell pomelo/grep"]),
    ("holba", "holba-serak-11", "Holba Šerák 11°", ["Holba Šerák", "Šerák", "Šerák 11"]),
    ("policka", "policka-otakar-11", "Polička Otakar 11°", ["Polička 11", "Otakar 11", "Otakar Polička 11"]),
    ("krusovice", "krusovice-bohem", "Krušovice Bohém", ["Bohém 11", "Bohém 12", "Krušovice Bohém 11", "Krušovice Bohém 12", "11° Bohém"]),
    ("poutnik", "poutnik-12", "Poutník 12°", ["Poutník světlý ležák – premium 12°"]),
    ("krakonos", "krakonos-12", "Krakonoš 12°", []),
    ("holba", "holba-keprnik-12", "Holba Keprník 12°", ["Holba Keprník", "Keprník 12", "Keprník", "Holba 12 Keprník"]),
    ("ostravar", "ostravar-mustang-11", "Ostravar Mustang 11°", ["Mustang 11"]),
    ("starobrno", "starobrno-statl-12", "Starobrno Štatl 12°", ["Štatl", "Štatl 12°", "Starobrno štatl"]),
    ("gambrinus", "gambrinus-nepasterizovana-11", "Gambrinus Nepasterizovaná 11°", []),
    ("svijany", "svijany-450", "Svijany 450", ["Svijanská 450°", "Svijany 450 Premium"]),
    ("ostravar", "ostravar-cerna-barbora", "Ostravar Černá Barbora", ["Černá Barbora", "Černá Barbora 13°"]),
    ("krusovice", "krusovice-nealko", "Krušovice Nealko", ["Krušovice Hořké nealko"]),
    ("gambrinus", "gambrinus-nepasterizovana-10", "Gambrinus Nepasterizovaná 10°", []),
    ("staropramen", "staropramen-cool-grep-nealko", "Staropramen Cool Grep Nealko", []),
    ("platan", "platan-11", "Platan 11°", ["Platan Jedenáctka"]),
    ("zubr", "zubr-grand-11", "Zubr Grand 11°", ["Zubr Grand"]),
    ("dalesice", "dalesice-11", "Dalešice 11°", ["Dalešická 11", "Dalešice Jedenáctka"]),
    ("hoegaarden", "hoegaarden-white", "Hoegaarden White", []),
    ("vinohradsky", "vinohradsky-11", "Vinohradská 11°", ["Vinohradský pivovar 11°", "Vinohrady 11°"]),
    ("primator", "primator-11", "Primátor 11°", []),
    ("uneticke", "uneticke-12", "Únětické pivo 12°", ["Únětice 12", "Únětická 12"]),
    ("zubr", "zubr-gold", "Zubr Gold", []),
    ("uneticke", "uneticke-10-7", "Únětické pivo 10,7°", ["Únětice 10,7", "Únětická 10,7"]),
    ("uneticke", "uneticke-10", "Únětické pivo 10°", ["Únětice 10", "Únětická 10", "Únětice 10° nefiltr"]),
    ("budweiser-budvar", "budweiser-budvar-krouzkovany", "Budweiser Budvar Kroužkovaný", ["Budvar Kroužkovaný", "Budvar original kroužkovaný", "Budvar Kroužek"]),
    ("pernstejn", "pernstejn-arnostova-horka-10", "Pernštejn Arnoštova hořká 10°", ["Arnoštova Hořká 10°", "Pernštejn Arnošt 10", "Arnošt hořký 10", "Arnošt 10"]),
    ("staropramen", "staropramen-nealko", "Staropramen Nealko", []),
    ("budweiser-budvar", "budweiser-budvar-nealko", "Budweiser Budvar Nealko", ["Budvar Nealko"]),
    ("lobkowicz", "lobkowicz-demon-13", "Lobkowicz Démon 13°", ["Démon 13°", "Démon 13° (polotmavý)"]),
    ("bernard", "bernard-free", "Bernard Free", []),
    ("policka", "policka-zavis-12", "Polička Záviš 12°", ["Polička 12"]),
    ("hubertus", "hubertus-11", "Hubertus 11°", ["Kácov 11"]),
    ("lomnicke", "lomnicke-lezak-11", "Lomnický ležák 11°", ["Lomnická 11", "Lomnické pivo sv. ležák 11°"]),
    ("jezek", "jezek-11", "Ježek 11°", []),
    ("konrad", "konrad-11", "Konrad 11°", ["Konrád 11°světlé"]),
    ("samson", "samson-11", "Samson 11°", []),
    ("rampusak", "rampusak-12", "Rampušák 12°", []),
    ("birgo", "birgo-mango-limetka", "Birgo Mango & Limetka", ["Birgo Mango a limetka"]),
    ("hauskrecht", "hauskrecht-brnenska-11", "Hauskrecht Brněnská 11°", ["Hauskrecht 11"]),
    ("krakonos", "krakonos-11", "Krakonoš 11°", []),
    ("bernard", "bernard-free-grep", "Bernard Free Grep", ["Bernard s čistou hlavou Grep", "Bernard grep"]),
    ("guinness", "guinness-draught", "Guinness Draught", []),
    ("bakalar", "bakalar-11", "Bakalář 11°", []),
    ("bernard", "bernard-nefiltrovana-12", "Bernard Nefiltrovaná 12°", ["Bernard 12° nefiltr"]),
    ("lomnicke", "lomnicke-summer-ale", "Lomnické pivo Summer Ale", ["Lomnický Summer Ale"]),
    ("gambrinus", "gambrinus-nefiltrovany-12", "Gambrinus Nefiltrovaný 12°", ["Gambrinus 12° nefiltr", "Gambrinus Nefiltr 12°", "Gambrinus Nefiltrovaný ležák, světlý ležák", "Gambrinus nefiltrovaný ležák", "Gambrinus Nefiltr"]),
    ("turnov", "turnov-dvanactka-12", "Turnovská Dvanáctka 12°", ["12° Turnovský ležák", "Turnovská 12°", "Turnov Turnovská dvanáctka", "Turnov světlá 12"]),
    ("rychtar", "rychtar-11", "Rychtář 11°", []),
    ("bernard", "bernard-cerna-12", "Bernard Černá 12°", []),
    ("bernard", "bernard-free-svestka", "Bernard Free Švestka", ["Bernard Švestka"]),
    ("pernstejn", "pernstejn-horka-12-ze-sklepa", "Pernštejn Hořká 12° ze sklepa", ["Pernštejn hořká 12°"]),
    ("staropramen", "staropramen-extra-chmel", "Staropramen Extra Chmel", []),
    ("ostravar", "ostravar-12", "Ostravar 12°", []),
    ("budweiser-budvar", "budweiser-budvar-redix", "Budweiser Budvar Redix", ["Budvar Redix"]),
    ("zlata-krava", "zlata-krava-plnotucna-12", "Zlatá kráva Plnotučná 12°", ["Plnotučná 12", "Plnotučná kráva", "Zlatá kráva - Plnotučná", "Zlatá Kráva 12 Plnotučná"]),
    ("poutnik", "poutnik-11", "Poutník 11°", ["Poutník světlý ležák 11°"]),
    ("nachmelena-opice", "nachmelena-opice-11", "Nachmelená Opice 11°", ["Nachmelená Opice Ležák 11%"]),
    ("dudak", "dudak-klostermann-polotmavy", "Dudák Klostermann Polotmavý", ["Klostermann polotmavý", "Klostermann polotmavý speciál", "Klostermann 13"]),
    ("ohrada", "ohrada-prasak-12", "Ohrada Prasák 12°", ["Prasák 12°"]),
    ("dalesice", "dalesice-osvald-10", "Dalešice Osvald 10°", ["Osvald 10°", "Osvald 10% (Dalešice)", "Osvlad 10°"]),
    ("pernstejn", "pernstejn-vilem-11", "Pernštejn Vilém 11°", ["Vilém 11"]),
    ("rychtar", "rychtar-grunt-11", "Rychtář Grunt 11°", ["Grunt 11"]),
    ("primator", "primator-tchyne", "Primátor Tchyně", ["11° Primátor IPL Tchyně", "Tchýně (Primátor)"]),
    ("turnov", "turnov-desitka-10", "Turnovská desítka 10°", ["Turnovská desítka", "Turnov Turnovská desítka", "10° Turnovská desítka"]),
    ("lobkowicz", "lobkowicz-premium-nealko", "Lobkowicz Premium Nealko", []),
    ("kutna-hora", "kutna-hora-zlata-12", "Kutná Hora Zlatá 12°", []),
    ("krusovice", "krusovice-original-10", "Krušovice Originál 10°", []),
    ("regent", "regent-11", "Regent 11°", ["Bohemia Regent 11°"]),
    ("zewl", "zewl-12", "Zewl 12°", []),
    ("velkopopovicky-kozel", "velkopopovicky-kozel-rezany", "Velkopopovický Kozel Řezaný", ["Kozel Řezaný"]),
    ("rohozec", "rohozec-cherry", "Rohozec Cherry Beer 10°", ["Rohozec Cherry"]),
    ("radegast", "radegast-nefiltrovana-12", "Radegast Nefiltrovaná 12°", ["Radek nefiltr 12°", "Radegast nefiltr"]),
    ("budweiser-budvar", "budweiser-budvar-vycepni", "Budweiser Budvar Výčepní", ["Budvar Výčepní", "Budvar 10°", "Budweiser Budvar 10"]),
    ("litovel", "litovel-moravan", "Litovel Moravan", []),
    ("samson", "samson-12", "Samson 12°", []),
    ("rebel", "rebel-11", "Rebel 11°", []),
    ("cvikov", "cvikov-klic-12", "Cvikov Klíč 12°", ["Klíč 12"]),
    ("pilsner-urquell", "pilsner-urquell-nefiltrovany", "Pilsner Urquell Nefiltrovaný", ["Pilsner Urquell - nefiltr", "Pilsner Urquell (nefiltrovaný ležák)", "Nefiltr Plzeň"]),
    ("chric", "chric-pazdrat-11", "Chříč Pazdrát 11°", ["Pazdrát 11", "Chříč 11"]),
    ("jarosovsky", "jarosovsky-stavbarova-11", "Stavbařova 11°", []),
    ("argus", "argus-12", "Argus 12°", []),
    ("dudak", "dudak-11", "Dudák 11°", ["Strakonický dudák 11°"]),
    ("morava", "morava-mango-10", "Morava Mango 10°", []),
    ("platan", "platan-starka", "Platan Starka", []),
    ("matuska", "matuska-california", "Matuška California", []),
    ("lucky-bastard", "lucky-bastard-blond-11", "Lucky Bastard Blond 11°", []),
    ("master", "master-tmavy-18", "Master Tmavý 18°", ["Master 18°"]),
    ("svijany", "svijany-desitka-10", "Svijanská Desítka 10°", ["Svijany Desítka 10", "Svijany 10°"]),
    ("jindra", "jindra-10", "Jindra 10°", []),
    ("zlatopramen", "zlatopramen-radler-tmavy-citron", "Zlatopramen Radler Tmavý citron", []),
    ("svijany", "svijany-vozka", "Svijany Vozka", []),
    ("staropramen", "staropramen-nefiltr", "Staropramen Nefiltr", []),
    ("pernstejn", "pernstejn-12", "Pernštejn 12°", []),
    ("lucky-bastard", "lucky-bastard-rocker-12", "Lucky Bastard Rocker 12°", ["Rocker 12"]),
    ("konicek", "konicek-ryzak-11", "Koníček Ryzák 11°", ["Koníček, Ryzák", "Koníček 11°"]),
    ("ostravar", "ostravar-mustang-12-horky", "Ostravar Mustang Hořký 12°", ["Ostravar Mustang 12 Hořký"]),
    ("samson", "samson-12-nefiltr", "Samson Nefiltrovaný 12°", ["Samson 12 nefiltr"]),
    ("rychtar", "rychtar-12", "Rychtář 12°", []),
    ("raven", "raven-12", "Raven 12°", []),
    ("rampusak", "rampusak-11", "Rampušák 11°", []),
    ("heineken", "heineken-original", "Heineken Original", []),
    ("corona", "corona-extra", "Corona Extra", []),
    ("svijany", "svijany-knezna-13", "Svijanská Kněžna 13°", ["Svijany Kněžna 13"]),
    ("beskydsky", "beskydsky-lezak", "Beskydský pivovárek Ležák", ["Beskydský Ležák", "Beskydský ležák 11°"]),
    ("falkenstejn", "falkenstejn-11", "Falkenštejn 11°", ["Falkenstein 11"]),
    ("vildenberg", "vildenberg-lezak-12", "Vildenberg Světlý ležák 12°", ["Vildenberg 12", "Vildenberský Ležák 12°", "Vildenberg Ležák"]),
    ("svijany", "svijany-vozka-yuzu-bergamot", "Svijany Vozka Yuzu & Bergamot", []),
    ("krusovice", "krusovice-psenicne", "Krušovice Pšeničné", []),
    ("bakalar", "bakalar-12", "Bakalář 12°", []),
    ("lomnicke", "lomnicke-12", "Lomnické pivo 12°", ["Lomnická 12"]),
    ("tri-sestry", "tri-sestry-lezak", "Tři Sestry Ležák", []),
    ("elektrarna", "elektrarna-ventill-11", "Elektrárna Ventill 11°", ["Ventill", "Elektrárna-ventil"]),
    ("matuska", "matuska-zlata-raketa-17", "Matuška Zlatá Raketa 17°", ["Zlatá raketa 17°", "Zlatá raketa"]),
    ("klaster", "klaster-11", "Klášter světlý ležák 11°", ["Klášter 11"]),
    ("primator", "primator-antonin-10", "Primátor Antonín 10°", ["Antonín 10°", "Primátor 10"]),
    ("rebel", "rebel-original-premium", "Rebel Original Premium", []),
    ("policka", "policka-hradebni-10", "Polička Hradební 10°", []),
    ("pernstejn", "pernstejn-10", "Pernštejn 10°", []),
    ("nachmelena-opice", "nachmelena-opice-ipa-14", "Nachmelená Opice IPA 14°", []),
    ("mordyr", "mordyr-11", "Mordýř 11°", []),
    ("krakonos", "krakonos-10", "Krakonoš 10°", []),
    ("holba", "holba-ryzi-nealko", "Holba Ryzí nealko", []),
    ("excelent", "excelent-11", "Excelent 11°", []),
    ("chotebor", "chotebor-premium-12", "Chotěboř Premium 12°", []),
    ("bernard", "bernard-jantarova-12", "Bernard Jantarová 12°", []),
    ("bakalar", "bakalar-10", "Bakalář 10°", []),
    ("argus", "argus-11", "Argus 11°", []),
    ("argus", "argus-10", "Argus 10°", []),
    ("jindra", "jindra-12", "Jindra světlý ležák 12°", ["Jindra 12°"]),
    ("hubertus", "hubertus-premium-12", "Hubertus Světlý ležák Prémium 12°", ["Hubertus 12", "Kácov 12°"]),
    ("cerna-hora", "cerna-hora-matous-11", "Černá Hora Matouš 11°", ["Matouš 11"]),
    ("litovel", "litovel-vyzrala-11", "Litovel Vyzrálá 11°", ["Litovel Extra Hořký Josef"]),
    ("pocernak", "pocernak-pocernicka-11", "Počernická 11°", []),
    ("nachmelena-opice", "nachmelena-opice-sun-apa-12", "Nachmelená Opice SUN APA 12°", ["Sun APA"]),
    ("zlata-labut", "zlata-labut-11", "Zlatá labuť 11°", []),
    ("vorkloster", "vorkloster-klasterni-10", "Vorkloster Klášterní 10°", []),
    ("rebel", "rebel-horka-11", "Rebel Hořká 11°", []),
    ("rebel", "rebel-12", "Rebel 12°", []),
    ("ostravar", "ostravar-10-vycepni", "Ostravar Výčepní 10°", ["Ostravar 10 Výčepní"]),
    ("litovel", "litovel-visen", "Litovel Višeň", []),
    ("krakonos", "krakonos-10-tmave", "Krakonoš Tmavé 10°", ["Krakonoš 10 tmavé"]),
    ("ferdinand", "ferdinand-max-11", "Ferdinand Max 11°", []),
    ("dalesice", "dalesice-12", "Dalešice Hořká 12°", ["Dalešice 12"]),
    ("cerna-hora", "cerna-hora-pater", "Černá Hora Páter", []),
    ("bradac", "bradac-12", "Bradáč 12°", []),
    ("argus", "argus-maestic-12", "Argus Maestic 12°", []),
    ("splavek", "splavek-12", "Splávek 12°", []),
    ("dudak", "dudak-kral-sumavy", "Dudák Král Šumavy", ["Král Šumavy"]),
    ("maisels-weisse", "maisels-weisse-alkoholfrei", "Maisel's Weisse Alkoholfrei", ["Maisel's Weisse Nealkoholické"]),
    ("zvikov", "zvikov-rarasek", "Zvíkovský Rarášek", []),
    ("urpiner", "urpiner-12", "Urpiner 12°", []),
    ("regent", "regent-12", "Regent 12°", []),
    ("maisels-weisse", "maisels-weisse-original", "Maisel's Weisse Original", []),
    ("litovel", "litovel-gustav-13", "Litovel Gustav 13°", []),
    ("litovel", "litovel-cerny-citron", "Litovel Černý citron", []),
    ("libertas", "libertas-12", "Libertas 12°", []),
    ("hostivar", "hostivar-11", "Hostivar Světlá 11°", ["Hostivař 11"]),
    ("holba", "holba-10", "Holba 10°", []),
    ("hoegaarden", "hoegaarden-rose", "Hoegaarden Rosé", []),
    ("cvikov", "cvikov-hvozd-11", "Cvikov Hvozd 11°", []),
    ("chotebor", "chotebor-11", "Chotěboř 11°", []),
    ("chodovar", "chodovar-11", "Chodovar 11°", []),
    ("cerna-hora", "cerna-hora-horka-11", "Černá Hora Hořká 11°", []),
    ("bernard", "bernard-cerna-lavina", "Bernard Černá lavina", []),
    ("postrizinske", "postrizinske-jedenactka", "Postřižinské pivo Jedenáctka", []),
    ("kbelsky", "kbelsky-11-pocestnych", "Kbelský pivovar 11 pocestných", ["11° Pocestných"]),
    ("zichovec", "zichovec-krahulik-11", "Zichovec Krahulík 11°", ["Krahulík 11°"]),
    ("dudak", "dudak-vycepni-10", "Dudák Výčepní", ["Dudák 10"]),
    ("plasy", "plasy-vasnosta-10", "Plasy Vašnosta 10°", ["Vašnosta 10°"]),
    ("fenek", "fenek-lezak-11", "Fenek Světlý ležák 11°", ["11 Ležák Fenek"]),
    ("moucha", "moucha-ceska-moucha-11", "Česká Moucha 11°", ["Moucha Česká Moucha 11°", "Moucha Světlý Ležák 11"]),
    ("pegas", "pegas-psenicne-12", "Pegas Pšeničné pivo 12°", ["Pegas Pšeničné pivo", "Pivo PEGAS - Pšeničné"]),
    ("trautenberk", "trautenberk-11", "Trautenberk 11°", []),
    ("turnov", "turnov-osmicka-8", "Turnovská osmička 8°", ["Turnov Turnovská osmička"]),
    ("turnov", "turnov-dvanactka-tmava-12", "Turnovská Dvanáctka tmavá 12°", ["Turnov Turnovská Dvanáctka tmavá"]),
    ("slavkov", "slavkov-12", "Slavkovská Dvanáctka 12°", ["Slavkov 12°"]),
    ("zubr", "zubr-gradus-12", "Zubr Gradus 12°", []),
    ("matuska", "matuska-dvanactka-12", "Matuška Dvanáctka 12°", ["Pivovar Matuška - Dvanáctka"]),
    ("dudak", "dudak-klostermann-svetly", "Dudák Klostermann Světlý", []),
    ("vltavotynsky", "vltavotynsky-svobodny-pan-10", "Vltavotýnský Svobodný pán 10°", ["Vltavotýnský Svobodný pán nefiltr"]),
    ("rohozec", "rohozec-skalak-11", "Rohozec Skalák 11°", []),
    ("senticky-kvasar", "senticky-kvasar-15", "Sentický Kvasar 15°", ["Kvasar 15"]),
    ("litovel", "litovel-svezi-pomelo-nealko", "Litovel Svěží pomelo", []),
    ("beskydsky", "beskydsky-boruvkovy-lezak-12", "Beskydský Borůvkový ležák 12°", ["Beskydský Borůvkový ležák"]),
    ("muflon", "muflon-11", "Muflon 11°", []),
    ("chodovar", "chodovar-nealkoholicke", "Chodovar Nealkoholické pivo", []),
    ("u-tomana", "u-tomana-tomanova-12", "Tomanova 12°", ["U Tomana Tomanova 12"]),
    ("bratcice", "bratcice-zamecka-11", "Bratčice Zámecká jedenáctka", []),
    ("bratcice", "bratcice-zamecka-12", "Bratčice Zámecká dvanáctka", []),
    ("vildenberg", "vildenberg-zlatak-11", "Vildenberský Zlaťák 11°", ["Vildenberg Zlaťák"]),
    ("tupadly", "tupadly-tupadelska-11", "Tupadelská 11°", []),
    ("dock7", "dock7-frajer-11", "Frajer 11°", []),
    ("kamenice-nad-lipou", "kamenice-kamenicka-11", "Kamenická 11°", []),
    ("morava", "morava-polotmava-11", "Morava Polotmavá 11°", []),
    ("zubr", "zubr-gral-10", "Zubr Grál 10°", []),
    ("zlata-krava", "zlata-krava-farm-apa-11", "Zlatá kráva Farm APA 11°", ["Zlatá Kráva 11 Farm APA"]),
    ("rohozec", "rohozec-vezak-10", "Rohozec Věžák 10°", []),
    ("plasy", "plasy-lothar-12", "Plasy Lothar 12°", ["Lothar 12°"]),
    ("cerna-hora", "cerna-hora-lezak-12", "Černá Hora Ležák 12°", []),
    ("chotebor", "chotebor-original-10", "Chotěboř Originál 10°", ["Chotěboř 10°"]),
    ("beskydsky", "beskydska-12-ale", "Beskydská 12° ALE", ["Beskydská 12"]),
    ("bratcice", "bratcice-zamecka-13", "Bratčice Zámecká třináctka", []),
    ("kutna-hora", "kutna-hora-stribrna-11", "Kutná Hora Stříbrná 11°", ["Kutná hora 11"]),
    ("svijany", "svijany-slik-11", "Svijany Šlik 11°", ["Svijany Šlik"]),
    ("moravia", "moravia-kluzak-11", "Moravia Kluzák 11°", []),
    ("plasy", "plasy-cisar-pan-14", "Plasy Císař pán 14°", ["Císař pán 14°"]),
    ("clock", "clock-krystus-nealko", "Clock Krystus", []),
    ("clock", "clock-anezka-11", "Clock Anežka 11°", ["Anežka 11°"]),
    ("rebel", "rebel-nealko", "Rebel Nealko", []),
    ("ferdinand", "ferdinand-premium-12", "Ferdinand Ležák světlý Premium 12°", ["Ferdinand Světlý ležák Premium 12"]),
    ("konicek", "konicek-grosak-14", "Koníček Grošák 14°", []),
    ("splavek", "splavek-10", "Splávek 10°", []),
    ("trautenberk", "trautenberk-polotmava-13", "Trautenberk Polotmavá 13°", ["Trautenberk polotmavá třináctka"]),
    ("svijany", "svijany-knize-13", "Svijanský Kníže 13°", []),
    ("hauskrecht", "hauskrecht-spilberk-10", "Hauskrecht Špilberk 10°", []),
    ("hauskrecht", "hauskrecht-brnenska-12", "Hauskrecht Brněnská 12°", ["Hauskrecht 12°"]),
    ("dalesice", "dalesice-majove-13", "Dalešické Májové 13°", ["Dalešice Májové 13"]),
    ("matuska", "matuska-raptor-15", "Matuška Raptor 15°", ["Raptor 15°"]),
    ("libertas", "libertas-apa-11", "Libertas APA 11°", ["APA Libertas 11"]),
    ("jindra", "jindra-11", "Jindra 11°", []),
    ("zlata-krava", "zlata-krava-tractor-ipa-14", "Zlatá kráva Tractor IPA 14°", ["Tractor IPA 14°"]),
    ("zlata-krava", "zlata-krava-yellow-cow-12", "Zlatá kráva Yellow Cow 12°", ["Yellow Cow 12°"]),
    ("zlata-krava", "zlata-krava-farm-dog-12", "Zlatá kráva Farm Dog 12°", ["Farm Dog 12°"]),
    ("jarosovsky", "jarosovsky-jura-11", "Jarošovský Jura 11°", []),
    ("dudak", "dudak-premium-12", "Dudák Premium", ["Dudák 12"]),
    ("plasy", "plasy-nachmelenec-11", "Plasy Nachmelenec 11°", ["Nachmelenec 11"]),
    ("plasy", "plasy-felcar-13", "Plasy Felčar 13°", ["Felčar 13°"]),
    ("klaster", "klaster-12", "Klášter Premium 12°", ["Klášter 12"]),
    ("lucky-bastard", "lucky-bastard-india-15", "Lucky Bastard India 15°", []),
    ("muflon", "muflon-albin-11", "Muflon Albín 11° ALE", ["Muflon Albín Ale"]),
    ("urpiner", "urpiner-extra-chmelena-14", "Urpiner Extra chmelená 14°", ["Urpiner 14°"]),
    ("u-tomana", "u-tomana-emanuelova-10", "Emanuelova 10°", []),
    ("vinohradsky", "vinohradsky-12", "Vinohradská 12°", []),
    ("samson", "samson-10", "Samson 10°", []),
    ("konrad", "konrad-12", "Konrad Světlý ležák 12°", ["Konrád 12"]),
    ("dock7", "dock7-docker-12", "DOCK7 Docker 12°", ["Docker 12°"]),
    ("spojovna", "spojovna-kunraticky-studak-11", "Kunratický Študák 11° ALE", ["Spojovna Kunratický Študák 11 ALE"]),
    ("volt", "volt-jiskra-11", "Volt Jiskra 11°", []),
    ("rudohor", "rudohor-gros-10", "Rudohor Groš 10°", []),
    ("rezek", "rezek-svetla-11", "Rezek 11° světlá", ["Rezek 11"]),
    ("platan", "platan-12", "Platan 12°", []),
    ("tisnov", "tisnov-tisnovan-12", "Tišnovan 12°", []),
    ("pegas", "pegas-gold-16", "Pegas Gold 16°", ["Pegas Speciál Gold"]),
    ("obora", "obora-srpena-11", "Obora Srpěna 11°", []),
    ("obora", "obora-jezibaba-12", "Obora Ježibaba 12°", ["Obora 12° Ježibaba"]),
    ("clock", "clock-hektor-10", "Clock Hektor 10°", ["Hektor 10"]),
    ("haksna", "haksna-clear-mind-nealko", "HAKSNA Clear Mind", ["HAKSNA non alcoholic lager"]),
    ("falkon", "falkon-krasohled-12", "Falkon Krasohled 12°", ["Falkon Krasohled"]),
    ("efi", "efi-summer-ale-10", "EFI Summer Ale", []),
    ("andelsky", "andelsky-andelska-11", "Andělská 11°", ["Andělský ležák 11"]),
    ("valaisanne", "valaisanne-lager", "Valaisanne Lager", []),
    ("rebel", "rebel-chevron-11", "Rebel Chevron 11°", []),
    ("kamenice-nad-lipou", "kamenice-kamenicka-10", "Kamenická 10°", []),
    ("kamenice-nad-lipou", "kamenice-kamenicka-12", "Kamenická 12°", []),
    ("slavkov", "slavkov-10", "Slavkovská desítka 10°", []),
    ("pernstejn", "pardubicky-porter-19", "Pardubický Porter 19°", ["Pardubický Porter"]),
]

# Spellings and nicknames of beers and brands already in the catalog.
PRODUCT_ALIASES = {
    "pilsner-urquell": ["Pilsner Urquell 12", "Pilsner Urquell světlý ležák", "Pilsner Urquell ležák", "Pilsner Urquel", "Pilsner Urqell", "Pillsner Urquel", "Plzeňský Prazdroj", "Plznička", "Plzeňka", "Plzínka", "Plzeňské", "Pilsner 12°", "12 Pilsner", "Pilsner urquel 12°", "Pilner Urquell", "Pirsnel urquel 12", "Plzeňské - Pilsner Urquell 12°", "Plzeň, světlý ležák", "Pilsner Urquell 0,5l", "Plznička 12"],
    "radegast-ryze-horka-12": ["Radegast Ryzí hořká 12", "Radek 12", "Radeček 12", "Radě 12", "12 Radegast", "Radegast Ryze hořká 12 - světlý ležák", "Radegast Ryzí hořká 12°u"],
    "radegast-razna-10": ["Radek 10", "Radeček 10", "Radě 10"],
    "radegast-ratar": ["Radegast Ratar 11"],
    "budweiser-budvar-original": ["Budvar 12"],
    "budweiser-budvar-33": ["Budvar 33 světlý ležák"],
    "krusovice-12": ["Krušovice Ležák 12"],
    "bernard-11": ["Bernard 11 světlé", "Bernard světlí ležák 11", "Bernard 11° čepovaný", "Bernard 11° 0,5l", "11° Bernard"],
    "svijany-maz-11": ["Svijany Máz 11", "Máz 11"],
    "bernard-12": ["Bernard 12° světlý ležák"],
    "svijany-rytir-12": ["Svijany Rytíř 12 %"],
    "velkopopovicky-kozel-11": ["Kozel 11° Medium"],
    "budweiser-budvar-dark": ["Budvar tmavý ležák"],
    "breznak-10": ["Březňák Světlé výčepní"],
    "gambrinus-10": ["Gambáč 10"],
    "gambrinus-11": ["Gambáč 11"],
    "gambrinus-12": ["Gambáč 12"],
    "staropramen-10": ["Staráč 10"],
    "staropramen-11": ["Staráč 11"],
    "staropramen-12": ["Staráč 12"],
    "breznak-11": ["11° Velké Březno"],
}
BRAND_ALIASES = {
    "hubertus": ["Kácov"],
    "postrizinske": ["Postřižiny"],
    "radegast": ["Radek", "Radka", "Radě", "Ráďula", "Radeček", "Radouš", "Radegastu", "Radko"],
    "staropramen": ["Staráč", "Starouš"],
    "branik": ["Brancl", "Braníček"],
    "krusovice": ["Kruše", "Krušky"],
    "gambrinus": ["Gambáč", "Gambrinuska"],
    "budweiser-budvar": ["Budvar"],
    "svijany": ["Svinany", "Sviany"],
    "bernard": ["Bernaded"],
    "bakalar": ["Balalář"],
    "pernstejn": ["Perštejn"],
}

# Official names that the earlier seed got wrong; the old name stays an alias.
PRODUCT_RENAMES = {
    "radegast-ryze-horka-12": "Radegast Ryze Hořká 12°",
}

# A bare "Birell" already means Birell Světlý, so a brand alias that lands on
# the brand name "Birell" would be rewritten a second time. These spellings
# move to the default product: brand key -> (product key, aliases to move).
BRAND_ALIASES_TO_PRODUCT = {
    "birell": ("birell-svetly", ["Birell nealko", "Radegast Birell"]),
}


def expand_catalog(apps, schema_editor):
    BeerBrand = apps.get_model("pubs", "BeerBrand")
    BeerProduct = apps.get_model("pubs", "BeerProduct")

    for index, (key, name, aliases) in enumerate(BRANDS):
        BeerBrand.objects.update_or_create(
            key=key,
            defaults={
                "name": name,
                "aliases": aliases,
                "rank": 800 + index * 10,
                "source_label": SOURCE_LABEL,
                "source_url": "",
                "active": True,
            },
        )

    brands = {brand.key: brand for brand in BeerBrand.objects.all()}
    for index, (brand_key, key, name, aliases) in enumerate(PRODUCTS):
        brand = brands.get(brand_key)
        if brand is None:
            # Only a database emptied after the earlier catalog seeds (tests).
            continue
        BeerProduct.objects.update_or_create(
            key=key,
            defaults={
                "brand": brand,
                "brand_key": brand.key,
                "brand_name": brand.name,
                "name": name,
                "aliases": aliases,
                "rank": 400 + index * 5,
                "source_label": SOURCE_LABEL,
                "source_url": "",
                "active": True,
            },
        )

    for key, name in PRODUCT_RENAMES.items():
        product = BeerProduct.objects.filter(key=key).first()
        if product is None or product.name == name:
            continue
        product.aliases = list(dict.fromkeys([*(product.aliases or []), product.name]))
        product.name = name
        product.save(update_fields=["name", "aliases", "updated_at"])

    for model, extra_aliases in ((BeerProduct, PRODUCT_ALIASES), (BeerBrand, BRAND_ALIASES)):
        for key, extra in extra_aliases.items():
            entity = model.objects.filter(key=key).first()
            if entity is None:
                continue
            entity.aliases = list(dict.fromkeys([*(entity.aliases or []), *extra]))
            entity.save(update_fields=["aliases", "updated_at"])

    for brand_key, (product_key, moved) in BRAND_ALIASES_TO_PRODUCT.items():
        brand = BeerBrand.objects.filter(key=brand_key).first()
        product = BeerProduct.objects.filter(key=product_key).first()
        if brand is None or product is None:
            continue
        brand.aliases = [alias for alias in brand.aliases or [] if alias not in moved]
        brand.save(update_fields=["aliases", "updated_at"])
        product.aliases = list(dict.fromkeys([*(product.aliases or []), *moved]))
        product.save(update_fields=["aliases", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("pubs", "0154_transit_feed"),
    ]

    operations = [
        migrations.RunPython(expand_catalog, migrations.RunPython.noop),
    ]
