# Generated by Django 6.1.1 on 2026-10-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0155_expand_beer_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('list', 'List of beers'), ('beer', 'Beer'), ('brand', 'Brand')], max_length=8)),
                ('key', models.SlugField(blank=True, max_length=100)),
                ('day', models.DateField()),
                ('data', models.JSONField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'key'), name='unique_beer_page')],
            },
        ),
    ]
