import { expect, secrets } from 'e2e';
import { test } from '../../helpers/test';
import { observer } from '../../helpers/backend';
import { openRoute, signIn, signInExisting } from '../../helpers/navigation';
import { addBeer, assertProfileName, openProfile, type IdentityState } from './helpers';

test('offline logout cannot deliver one account history to the next account', { tags: ['critical', 'full', 'identity'] }, async (ui) => {
  const { app, screen, local } = ui;
  await local.reset('identity');
  await signIn(ui);
  await addBeer(ui);
  await expect.poll(async () => (await local.state<IdentityState>()).scenario.accounts.find(a => a.nickname === 'E2EPivar')?.drinks.length).toBe(2);
  await local.offline();
  await addBeer(ui);
  await openRoute(ui, '/account');
  await screen.getByRole('button', 'Odhlásit se').tap();
  await expect(screen.getByRole('button', 'Odhlásit se')).not.toBeVisible();
  await app.restart();
  await openProfile(ui);
  await expect(screen.getByRole('button', 'Vytvořit účet')).toBeVisible();
  await local.online();
  await signInExisting(ui, 'secondEmail');
  await app.restart();
  await assertProfileName(ui, 'E2E second');
  const state = (await local.state<IdentityState>()).scenario;
  expect(state.accounts.find(a => a.nickname === 'E2EPivar')?.drinks.map(d => d.beerName)).toEqual(['E2E Archiv A', 'E2E Ležák']);
  expect(state.accounts.find(a => a.nickname === 'E2EKamarad')?.drinks.map(d => d.beerName)).toEqual(['E2E Archiv B']);
  expect(state.accounts.filter(a => !a.nickname).flatMap(a => a.drinks)).toEqual([]);
  local.screenshot('identity-next-account-isolated');
});

test('account deletion requires confirmation and revokes existing sessions', { tags: ['critical', 'full', 'identity'] }, async (ui) => {
  const { app, screen, local } = ui;
  await local.reset('identity');
  await signIn(ui);
  const priorSession = await observer();
  await openRoute(ui, '/account');
  await screen.getByRole('button', 'Otevřít další možnosti účtu').tap();
  await screen.getByRole('button', 'Smazat účet').tap();
  await screen.getByRole('button', 'Zrušit').tap();
  expect((await local.state<IdentityState>()).scenario.accounts.find(a => a.nickname === 'E2EPivar')?.status).toBe('active');
  expect((await priorSession.get('/v1/account/me')).status).toBe(200);
  await screen.getByRole('button', 'Otevřít další možnosti účtu').tap();
  await screen.getByRole('button', 'Smazat účet').tap();
  await screen.getByRole('button', 'Smazat').tap();
  await expect.poll(async () => (await local.state<IdentityState>()).scenario.accounts.find(a => a.nickname === 'E2EPivar')?.status).toBe('pending_deletion');
  await app.restart();
  await openProfile(ui);
  await expect(screen.getByRole('button', 'Vytvořit účet')).toBeVisible();
  const account = (await local.state<IdentityState>()).scenario.accounts.find(a => a.nickname === 'E2EPivar');
  expect(account?.status).toBe('pending_deletion');
  expect(account?.deleted).toBe(true);
  expect(account?.sessionTokens).toBe(0);
  expect((await priorSession.get('/v1/account/me')).status).toBe(401);
  local.screenshot('identity-account-deleted');
});

test('real email password reset rejects the old password and old session', { tags: ['critical', 'full', 'identity'] }, async (ui) => {
  const { app, screen, local } = ui;
  await local.reset('identity');
  await signIn(ui);
  const priorSession = await observer();
  await openRoute(ui, '/account');
  await screen.getByRole('button', 'Odhlásit se').tap();
  await openRoute(ui, '/auth');
  await screen.getByTestId('auth-reset-open').tap();
  await screen.getByTestId('auth-reset-email').fill(secrets.get('email'));
  await screen.getByTestId('auth-reset-request').tap();
  await expect.poll(async () => (await local.state<IdentityState>()).scenario.mail.reset).toBe(1);
  await screen.getByTestId('reset-code').fill(secrets.get('resetCode'));
  await screen.getByTestId('reset-password').fill(secrets.get('newPassword'));
  await screen.getByTestId('reset-submit').tap();
  await expect(screen.getByTestId('reset-submit')).not.toBeVisible();
  await app.restart();
  await assertProfileName(ui, 'E2E Pivař');
  expect((await priorSession.get('/v1/account/me')).status).toBe(401);
  const account = (await local.state<IdentityState>()).scenario.accounts.find(a => a.nickname === 'E2EPivar');
  expect(account?.originalPasswordWorks).toBe(false);
  expect(account?.newPasswordWorks).toBe(true);
  expect(account?.oneTimeTokens.find(token => token.purpose === 'reset_password')?.used).toBe(true);
  await openRoute(ui, '/account');
  await screen.getByRole('button', 'Odhlásit se').tap();
  await openRoute(ui, '/auth');
  await screen.getByTestId('auth-email').fill(secrets.get('email'));
  await screen.getByTestId('auth-password').fill(secrets.get('password'));
  await screen.getByTestId('auth-submit').tap();
  await expect(screen.getByTestId('auth-error')).toBeVisible();
  await screen.getByTestId('auth-password').fill(secrets.get('newPassword'));
  await screen.getByTestId('auth-submit').tap();
  await expect(screen.getByTestId('auth-submit')).not.toBeVisible();
  await assertProfileName(ui, 'E2E Pivař');
  expect((await local.state<IdentityState>()).scenario.accounts.find(a => a.nickname === 'E2EPivar')?.drinks.map(d => d.beerName)).toEqual(['E2E Archiv A']);
  local.screenshot('identity-password-reset');
});
