import { expect } from 'e2e';
import { test } from '../../helpers/test';
import { observer } from '../../helpers/backend';
import { addGalleryFixtures, restartWithPermissions } from '../../helpers/media';
import { openRoute, signIn } from '../../helpers/navigation';
import { openProfile, type IdentityState, type UI } from './helpers';

async function pickGalleryPhoto(ui: UI) {
  await ui.screen.getByRole('button', 'Vybrat z galerie').tap();
  await ui.agent.act('V nativním výběru fotek vyber první dostupnou testovací fotku. Jsou tu jen dvě syntetické E2E fixture. Potvrď výběr, pokud to systém požaduje. Nezapínej oznámení a nenaviguj jinam.');
  await expect(ui.screen.getByRole('textbox', 'Popisek fotky')).toBeVisible();
}

test('native avatar upload persists and removal survives restart', { tags: ['full', 'identity'] }, async (ui) => {
  const { screen, app, local } = ui;
  await local.reset('identity');
  addGalleryFixtures();
  await signIn(ui);
  await openRoute(ui, '/profile/edit');
  await screen.getByTestId('profile-avatar-pick').tap();
  await ui.agent.act('V nativním výběru fotek zvol první dostupnou syntetickou E2E fotku. Potvrď čtvercový výřez tlačítkem Choose nebo Vybrat. Vrať se do editoru profilu.');
  await expect.poll(async () => (await local.state<IdentityState>()).scenario.accounts.find(a => a.nickname === 'E2EPivar')?.avatarFileExists).toBe(true);
  await app.restart();
  await openProfile(ui);
  await openRoute(ui, '/profile/edit');
  await expect(screen.getByTestId('profile-avatar-remove')).toBeVisible();
  await screen.getByTestId('profile-avatar-remove').tap();
  await expect.poll(async () => (await local.state<IdentityState>()).scenario.accounts.find(a => a.nickname === 'E2EPivar')?.hasAvatar).toBe(false);
  await app.restart();
  await openProfile(ui);
  await openRoute(ui, '/profile/edit');
  await expect(screen.getByTestId('profile-avatar-remove')).not.toBeVisible();
  await screen.getByRole('button', 'Zavřít').tap();
  await openProfile(ui);
  local.screenshot('identity-avatar-removed');
});

test('offline native photo survives restart and friends never receive private photos', { tags: ['critical', 'full', 'identity'] }, async (ui) => {
  const { screen, app, local } = ui;
  await local.reset('identity');
  addGalleryFixtures();
  await signIn(ui);
  const friend = await observer('second');
  const outsider = await observer('outsider');
  const primaryId = (await local.state()).accounts.find(a => a.nickname === 'E2EPivar')!.publicId;
  await openRoute(ui, '/profile/photos');
  await screen.getByRole('button', 'Přidat fotku piva').tap();
  await pickGalleryPhoto(ui);
  await screen.getByRole('textbox', 'Popisek fotky').fill('E2E soukromá');
  await screen.getByRole('radio', 'Viditelnost fotky: Jen pro mě').tap();
  await local.offline();
  await screen.getByRole('button', 'Uložit do deníčku').tap();
  await expect(screen.getByRole('button', 'Fotka piva, E2E soukromá. Ťukni pro detail.')).toBeVisible();
  await app.restart();
  await openProfile(ui);
  await openRoute(ui, '/profile/photos');
  await expect(screen.getByRole('button', 'Fotka piva, E2E soukromá. Ťukni pro detail.')).toBeVisible();
  await local.online();
  await app.restart();
  await openProfile(ui);
  await openRoute(ui, '/profile/photos');
  await expect.poll(async () => (await local.state<IdentityState>()).scenario.accounts.find(a => a.nickname === 'E2EPivar')?.photos.length).toBe(1);
  const privatePhoto = (await local.state<IdentityState>()).scenario.accounts.find(a => a.nickname === 'E2EPivar')!.photos[0];
  expect(privatePhoto.caption).toBe('E2E soukromá');
  expect(privatePhoto.visibility).toBe('private');
  expect(privatePhoto.fileExists).toBe(true);
  await screen.getByRole('button', 'Přidat fotku piva').tap();
  await pickGalleryPhoto(ui);
  await screen.getByRole('textbox', 'Popisek fotky').fill('E2E pro partu');
  await screen.getByRole('button', 'Uložit do deníčku').tap();
  await expect.poll(async () => (await local.state<IdentityState>()).scenario.accounts.find(a => a.nickname === 'E2EPivar')?.photos.length).toBe(2);
  const friendsView = await friend.get(`/v1/friends/${primaryId}/beer-photos`);
  expect(friendsView.status).toBe(200);
  expect((friendsView.body as { photos: { caption: string }[] }).photos.map(p => p.caption)).toEqual(['E2E pro partu']);
  expect((await outsider.get(`/v1/friends/${primaryId}/beer-photos`)).status).toBe(404);
  const feed = await friend.get('/v1/friends/beer-photos/feed');
  expect(JSON.stringify(feed.body).includes('E2E soukromá')).toBe(false);
  await screen.getByTestId(`photo-item-${privatePhoto.clientId}`).tap();
  await screen.getByRole('button', 'Smazat fotku').tap();
  await screen.getByRole('button', 'Nechat').tap();
  expect((await local.state<IdentityState>()).scenario.accounts.find(a => a.nickname === 'E2EPivar')?.photos).toHaveLength(2);
  await screen.getByRole('button', 'Smazat fotku').tap();
  await screen.getByRole('button', 'Smazat').tap();
  await app.restart();
  await openProfile(ui);
  await openRoute(ui, '/profile/photos');
  await expect(screen.getByTestId(`photo-item-${privatePhoto.clientId}`)).not.toBeVisible();
  expect((await local.state<IdentityState>()).scenario.accounts.find(a => a.nickname === 'E2EPivar')?.photos.map(p => p.caption)).toEqual(['E2E pro partu']);
  local.screenshot('identity-photo-private-isolated');
});

test('denied media permissions and picker cancel keep the profile usable', { tags: ['full', 'identity'] }, async (ui) => {
  const { screen, device, local } = ui;
  await local.reset('identity');
  addGalleryFixtures();
  await signIn(ui);
  await restartWithPermissions(device, { photos: 'deny', camera: 'deny' });
  await openProfile(ui);
  await openRoute(ui, '/profile/edit');
  await screen.getByTestId('profile-avatar-pick').tap();
  await expect(screen.getByRole('button', 'Otevřít Nastavení')).toBeVisible();
  await screen.getByRole('textbox', 'Jméno').fill('E2E Bez fotky');
  await screen.getByTestId('profile-save').tap();
  await expect(screen.getByTestId('profile-save')).not.toBeVisible();
  await openRoute(ui, '/profile/photos');
  await screen.getByRole('button', 'Přidat fotku piva').tap();
  await screen.getByRole('button', 'Vyfotit pivo').tap();
  if (await screen.getByRole('button', 'Zrušit').isVisible()) await screen.getByRole('button', 'Zrušit').tap();
  if (await screen.getByRole('button', 'Zavřít fotku').isVisible()) await screen.getByRole('button', 'Zavřít fotku').tap();
  await restartWithPermissions(device, { photos: 'grant', camera: 'deny' });
  await openProfile(ui);
  await openRoute(ui, '/profile/photos');
  await screen.getByRole('button', 'Přidat fotku piva').tap();
  await screen.getByRole('button', 'Vybrat z galerie').tap();
  await ui.agent.act('Zruš nativní výběr fotky tlačítkem Cancel nebo Zrušit. Potom zavři nabídku zdroje fotky, pokud zůstala otevřená. Žádnou fotku nevybírej.');
  await openProfile(ui);
  const account = (await local.state<IdentityState>()).scenario.accounts.find(a => a.nickname === 'E2EPivar');
  expect(account?.displayName).toBe('E2E Bez fotky');
  expect(account?.hasAvatar).toBe(false);
  expect(account?.photos).toEqual([]);
  local.screenshot('identity-media-denied-recovered');
});
