import { expect, secrets } from 'e2e';
import { test } from '../../helpers/test';
import { observer } from '../../helpers/backend';
import { verifyEmail } from '../../helpers/mail';
import { openRoute, signInExisting, skipOnboarding } from '../../helpers/navigation';
import { addBeer, assertProfileName, openProfile, type IdentityState } from './helpers';

test('registration claims anonymous history and real email unlocks export', { tags: ['critical', 'full', 'identity'] }, async (ui) => {
  const { app, screen, local } = ui;
  await local.reset('registration');
  await skipOnboarding(ui);
  await addBeer(ui);
  await expect.poll(async () => (await local.state()).accounts.find(a => !a.registered)?.drinks.length).toBe(1);
  const anonymousId = (await local.state()).accounts.find(a => !a.registered)!.publicId;
  await local.offline();
  await addBeer(ui);
  await local.online();
  await openRoute(ui, '/auth');
  await screen.getByTestId('auth-register-mode').tap();
  await screen.getByRole('textbox', 'Přezdívka').fill('E2ERegister');
  await screen.getByTestId('auth-email').fill(secrets.get('email'));
  await screen.getByTestId('auth-password').fill(secrets.get('password'));
  await screen.getByTestId('auth-submit').tap();
  await screen.getByRole('radio', 'Jen pro partu. Veřejně tě nikdo nenajde. Profil uvidí jen tvoji kamarádi.').tap();
  await screen.getByRole('button', 'Potvrdit a jít na pivo').tap();
  await expect.poll(async () => (await local.state<IdentityState>()).scenario.accounts.find(a => a.nickname === 'E2ERegister')?.isPublic).toBe(false);
  await app.restart();
  await openProfile(ui);
  await expect(screen.getByRole('button', 'Upravit profil')).toBeVisible();
  await expect.poll(async () => (await local.state<IdentityState>()).scenario.accounts.find(a => a.nickname === 'E2ERegister')?.drinks.length).toBe(2);
  let state = await local.state<IdentityState>();
  expect(state.scenario.accounts.find(a => a.nickname === 'E2ERegister')?.publicId).toBe(anonymousId);
  expect(state.scenario.accounts.find(a => a.nickname === 'E2ERegister')?.isPublic).toBe(false);
  expect(state.accounts.find(a => a.nickname === 'E2ERegister')?.verified).toBe(false);
  const stranger = await observer('outsider');
  expect((await stranger.get(`/v1/friends/${anonymousId}`)).status).toBe(404);
  await openRoute(ui, '/account');
  await screen.getByRole('button', 'Otevřít další možnosti účtu').tap();
  await screen.getByRole('button', 'Stáhnout moje data').tap();
  expect((await local.state<IdentityState>()).scenario.mail.exports).toHaveLength(0);
  await verifyEmail();
  await app.restart();
  await openRoute(ui, '/account');
  await screen.getByRole('button', 'Otevřít další možnosti účtu').tap();
  await screen.getByRole('button', 'Stáhnout moje data').tap();
  await expect.poll(async () => (await local.state<IdentityState>()).scenario.mail.exports.length).toBe(1);
  state = await local.state<IdentityState>();
  expect(state.accounts.find(a => a.nickname === 'E2ERegister')?.verified).toBe(true);
  expect(state.scenario.mail.exports[0].publicId).toBe(anonymousId);
  expect(state.scenario.mail.exports[0].drinks.map(d => d.beerName)).toEqual(['E2E Ležák', 'E2E Ležák']);
  expect(state.scenario.accounts.find(a => a.nickname === 'E2ERegister')?.oneTimeTokens.find(t => t.purpose === 'verify_email')?.used).toBe(true);
  await openProfile(ui);
  local.screenshot('identity-registered-private-verified');
});

test('profile edits persist and a private profile stays hidden from outsiders', { tags: ['critical', 'full', 'identity'] }, async (ui) => {
  const { app, screen, local } = ui;
  await local.reset('identity');
  await skipOnboarding(ui);
  await signInExisting(ui);
  const outsider = await observer('outsider');
  const primaryId = (await local.state()).accounts.find(a => a.nickname === 'E2EPivar')!.publicId;
  expect((await outsider.get(`/v1/friends/${primaryId}`)).status).toBe(200);
  await openRoute(ui, '/profile/edit');
  await screen.getByRole('textbox', 'Přezdívka').fill('E2EKamarad');
  await expect(screen.getByText('Tahle přezdívka je zabraná')).toBeVisible();
  await screen.getByRole('textbox', 'Přezdívka').fill('E2EUpdated');
  await screen.getByRole('textbox', 'Jméno').fill('E2E Upravený');
  await screen.getByTestId('profile-public').tap();
  await screen.getByTestId('profile-save').tap();
  await expect(screen.getByTestId('profile-save')).not.toBeVisible();
  await app.restart();
  await assertProfileName(ui, 'E2E Upravený');
  const account = (await local.state<IdentityState>()).scenario.accounts.find(a => a.publicId === primaryId);
  expect(account?.nickname).toBe('E2EUpdated');
  expect(account?.displayName).toBe('E2E Upravený');
  expect(account?.isPublic).toBe(false);
  expect((await outsider.get(`/v1/friends/${primaryId}`)).status).toBe(404);
  expect(account?.drinks.map(d => d.beerName)).toEqual(['E2E Archiv A']);
  local.screenshot('identity-profile-private');
});
