import { expect } from 'e2e';
import { test } from '../../helpers/test';
import { observer } from '../../helpers/backend';
import { openRoute, signIn } from '../../helpers/navigation';
import { assertProfileName, openProfile, reveal, type IdentityState } from './helpers';

test('server and local settings survive restart and language reload', { tags: ['full', 'identity'] }, async (ui) => {
  const { app, screen, local } = ui;
  await local.reset('identity');
  await signIn(ui);
  await openRoute(ui, '/settings');
  await screen.getByTestId('settings-hide-names').tap();
  await reveal(screen, screen.getByTestId('settings-haptics'));
  await screen.getByTestId('settings-haptics').tap();
  await reveal(screen, screen.getByTestId('settings-water'));
  await screen.getByTestId('settings-water').tap();
  await expect.poll(async () => (await local.state<IdentityState>()).scenario.accounts.find(a => a.nickname === 'E2EPivar')?.settings).toEqual({ hidePubNames: true, hapticEnabled: false, marketingEmailsEnabled: false });
  await app.restart();
  await openProfile(ui);
  await openRoute(ui, '/settings');
  await expect(screen.getByTestId('settings-hide-names')).toBeChecked();
  await reveal(screen, screen.getByTestId('settings-haptics'));
  await expect(screen.getByTestId('settings-haptics')).toBeChecked({ checked: false });
  await reveal(screen, screen.getByTestId('settings-water'));
  await expect(screen.getByTestId('settings-water')).toBeChecked();
  await reveal(screen, screen.getByTestId('settings-language-en'));
  await screen.getByTestId('settings-language-en').tap();
  await openRoute(ui, '/settings');
  await expect(screen.getByRole('button', 'Back')).toBeVisible({ timeout: 60_000 });
  await app.restart();
  await openProfile(ui);
  await openRoute(ui, '/settings');
  await expect(screen.getByRole('button', 'Back')).toBeVisible();
  await reveal(screen, screen.getByTestId('settings-water'));
  await expect(screen.getByTestId('settings-water')).toBeChecked();
  await reveal(screen, screen.getByTestId('settings-language-cs'));
  await screen.getByTestId('settings-language-cs').tap();
  await openRoute(ui, '/settings');
  await expect(screen.getByRole('button', 'Zpět')).toBeVisible({ timeout: 60_000 });
  await assertProfileName(ui, 'E2E Pivař');
  const primary = await observer();
  expect((await primary.get('/v1/account/me')).status).toBe(200);
  local.screenshot('identity-settings-persisted');
});

test('profile badges match server and local information screens remain usable offline', { tags: ['full', 'identity'] }, async (ui) => {
  const { screen, app, local } = ui;
  await local.reset('identity');
  await signIn(ui);
  const primary = await observer();
  const response = await primary.get('/v1/account/me');
  expect((response.body as { achievements: { foto_pivar: boolean } }).achievements.foto_pivar).toBe(true);
  await openRoute(ui, '/profile/badges');
  await reveal(screen, screen.getByRole('image', 'FotoPivař, splněno'));
  await app.restart();
  await openProfile(ui);
  await openRoute(ui, '/profile/badges');
  await reveal(screen, screen.getByRole('image', 'FotoPivař, splněno'));
  await openRoute(ui, '/about');
  await reveal(screen, screen.getByText('E2E místní novinky').first());
  await local.offline();
  await openRoute(ui, '/privacy');
  await expect(screen.getByRole('button', 'Zpět')).toBeVisible();
  await screen.getByRole('button', 'Zpět').tap();
  await openProfile(ui);
  await expect(screen.getByRole('button', 'Upravit profil')).toBeVisible();
  await local.online();
  expect((await primary.get('/v1/account/me')).status).toBe(200);
  local.screenshot('identity-profile-badges-information');
});
