import { expect } from 'e2e';
import { test } from '../../helpers/test';
import { observer } from '../../helpers/backend';
import { dismissPubReminder, openRoute, signIn } from '../../helpers/navigation';

type Row = Record<string, string | boolean>;
type SocialState = {
  fixtureAccounts: Record<string, string>; eventId: string; inviteCode: string; requestId: string; events: Row[];
  memberships: Row[]; friendships: Row[]; blocks: Row[];
  photos: Row[]; entries: Row[]; votes: Row[];
};
type EventBody = { exactAddressPresent: boolean; membership_status: string };
type BoardBody = { period: string; entries: { score: number; account: { nickname: string } }[] };

test('host approval reveals the event address only to the approved guest', { tags: ['critical', 'full'] }, async ({ app, screen, device, local }) => {
  await local.reset('places_social');
  await signIn({ app, screen, device });
  const state = (await local.state<SocialState>()).scenario;
  const guest = await observer('second');
  const outsider = await observer('outsider');
  const before = await guest.get(`/v1/community-events/${state.eventId}`);
  expect(before.status).toBe(200);
  expect((before.body as EventBody).exactAddressPresent).toBe(false);
  await openRoute({ device, screen }, '/community-events');
  await screen.getByLabel('Moje').tap();
  const approve = screen.getByTestId(`community-request-${state.requestId}-approve`);
  await screen.scrollUntilVisible(approve, { direction: 'down' });
  await approve.tap();
  await expect.poll(async () => (await local.state<SocialState>()).scenario.memberships).toEqual([{ account__nickname: 'E2EKamos', status: 'approved' }]);
  const approved = await guest.get(`/v1/community-events/${state.eventId}`);
  expect(approved.status).toBe(200);
  expect((approved.body as EventBody).exactAddressPresent).toBe(true);
  const stranger = await outsider.get(`/v1/community-events/${state.eventId}`);
  expect(stranger.status).toBe(200);
  expect((stranger.body as EventBody).exactAddressPresent).toBe(false);
  const cancel = screen.getByText('Zrušit setkání');
  await screen.scrollUntilVisible(cancel, { direction: 'down' });
  await cancel.tap();
  await expect.poll(async () => ((await guest.get(`/v1/community-events/${state.eventId}`)).body as EventBody).exactAddressPresent).toBe(false);
  await expect.poll(async () => (await local.state<SocialState>()).scenario.events).toEqual([{ title: 'E2E Večer u hosta', status: 'cancelled' }]);
  await expect(screen.getByText('Zrušit setkání')).not.toBeVisible();
  const status = screen.getByTestId(`community-event-${state.eventId}-status`);
  await screen.scrollUntilVisible(status, { direction: 'up' });
  await expect(status).toHaveText('Setkání je zrušené.');
  await expect(screen.getByText('poslední místo · Pořádá @E2EPivar')).not.toBeVisible();
  await expect(screen.getByText('Máš místo')).not.toBeVisible();
  local.screenshot('social-event-cancelled');
});

test('sharing, ghost and blocking remove private activity from the real friend API', { tags: ['critical', 'full'] }, async ({ app, screen, agent, device, local }) => {
  await local.reset('places_social');
  await signIn({ app, screen, device });
  const ids = (await local.state<SocialState>()).scenario.fixtureAccounts;
  const friend = await observer('second');
  const outsider = await observer('outsider');
  const baseline = await friend.get('/v1/friends/live');
  expect(baseline.status).toBe(200);
  expect(JSON.stringify(baseline.body)).toContain('E2EPivar');
  const sharedDrinks = await friend.get('/v1/friends/drink-feed');
  expect(sharedDrinks.status).toBe(200);
  expect(JSON.stringify(sharedDrinks.body)).toContain('E2EPivar');
  expect((await outsider.get(`/v1/friends/${ids.E2EKamos}`)).status).toBe(200);
  const primary = await observer('primary');
  expect((await primary.get(`/v1/friends/${ids.E2ECizi}`)).status).toBe(404);
  await openRoute({ device, screen }, '/friends');
  local.screenshot('social-party-settings-before');
  await expect(screen.getByRole('button', 'Co ještě? Nastavení, žebříčky a další')).toBeVisible();
  await agent.act('V Partě otevři nastavení party. Vypni Ukazovat partě, kde sedím. Potom zavři nastavení.');
  await expect.poll(async () => (await local.state()).accounts.find(a => a.nickname === 'E2EPivar')?.shareDrinks).toBe(false);
  const hiddenLive = await friend.get('/v1/friends/live');
  const hiddenDrinks = await friend.get('/v1/friends/drink-feed');
  expect(hiddenLive.status).toBe(200);
  expect(hiddenDrinks.status).toBe(200);
  expect(JSON.stringify(hiddenLive.body)).not.toContain('E2EPivar');
  expect(JSON.stringify(hiddenDrinks.body)).not.toContain('E2EPivar');
  await agent.act('V nastavení party znovu zapni Ukazovat partě, kde sedím a zároveň zapni Neviditelný režim. Potom zavři nastavení.');
  await expect.poll(async () => (await local.state()).accounts.find(a => a.nickname === 'E2EPivar')?.shareDrinks).toBe(true);
  await expect.poll(async () => (await local.state()).accounts.find(a => a.nickname === 'E2EPivar')?.ghostMode).toBe(true);
  const live = await friend.get('/v1/friends/live');
  const drinks = await friend.get('/v1/friends/drink-feed');
  expect(live.status).toBe(200);
  expect(drinks.status).toBe(200);
  expect(JSON.stringify(live.body)).not.toContain('E2EPivar');
  expect(JSON.stringify(drinks.body)).not.toContain('E2EPivar');
  await openRoute({ device, screen }, `/parta/${ids.E2EKamos}`);
  await agent.act('V profilu E2EKamos otevři možnosti a zablokuj tohoto uživatele. Potvrď blokování.');
  await expect.poll(async () => (await local.state<SocialState>()).scenario.blocks).toEqual([{ blocker__nickname: 'E2EPivar', blocked__nickname: 'E2EKamos' }]);
  expect((await friend.get(`/v1/friends/${ids.E2EPivar}`)).status).toBe(404);
  expect((await local.state<SocialState>()).scenario.friendships).toEqual([]);
  await app.restart();
  await dismissPubReminder({ screen });
  await openRoute({ device, screen }, '/friends');
  await agent.assert('Parta po restartu neobsahuje E2EKamos jako kamaráda.');
  local.screenshot('social-blocked-party');
});

test('invite claim creates one accepted relationship and party survives offline restart', { tags: ['full'] }, async ({ app, screen, agent, device, local }) => {
  await local.reset('places_social');
  await signIn({ app, screen, device });
  const fixture = (await local.state<SocialState>()).scenario;
  await openRoute({ device, screen }, `/parta/pozvanka?code=${fixture.inviteCode}`);
  await agent.act('Přidej E2ECizi do party tlačítkem na pozvánce.');
  await expect.poll(async () => (await local.state<SocialState>()).scenario.friendships.filter(row => row.recipient__nickname === 'E2ECizi')).toEqual([{ requester__nickname: 'E2EPivar', recipient__nickname: 'E2ECizi', status: 'accepted' }]);
  await openRoute({ device, screen }, '/friends');
  await agent.assert('Parta obsahuje kámoše E2EKamos i E2ECizi přidaného pozvánkou.');
  await local.offline();
  await app.restart();
  await dismissPubReminder({ screen });
  await openRoute({ device, screen }, '/friends');
  await agent.assert('Poslední načtená Parta obsahuje E2EKamos i E2ECizi bez serveru po restartu.');
  local.screenshot('social-offline-party');
  await local.online();
  expect((await local.state<SocialState>()).scenario.friendships).toHaveLength(2);
});

test('leaderboard shows exact fixture scores and never lists the private outsider', { tags: ['critical', 'full'] }, async ({ app, screen, agent, device, local }) => {
  await local.reset('places_social');
  await signIn({ app, screen, device });
  const primary = await observer();
  const before = await primary.get('/v1/leaderboards?category=beers&period=week');
  expect(before.status).toBe(200);
  expect((before.body as BoardBody).entries.map(row => [row.account.nickname, row.score])).toEqual([['E2EKamos', 2], ['E2EPivar', 1]]);
  await openRoute({ device, screen }, '/leaderboards');
  await agent.assert('Žebříček pivařů za tento týden má E2EKamos se dvěma pivy a vlastní řádek Ty s jedním pivem. Soukromý E2ECizi zde není.');
  await agent.act('Přepni žebříček na Mapéři.');
  await agent.assert('Žebříček Mapérů ukazuje E2EKamos s 20 XP a vlastní řádek Ty s 10 XP.');
  const mapper = await primary.get('/v1/leaderboards?category=mapper&period=week');
  expect((mapper.body as BoardBody).period).toBe('all');
  expect((mapper.body as BoardBody).entries.map(row => [row.account.nickname, row.score])).toEqual([['E2EKamos', 20], ['E2EPivar', 10]]);
  const id = (await local.state<SocialState>()).scenario.fixtureAccounts.E2EKamos;
  await openRoute({ device, screen }, `/parta/${id}`);
  await agent.act('V profilu E2EKamos otevři možnosti a zablokuj tohoto uživatele. Potvrď blokování.');
  await expect.poll(async () => (await local.state<SocialState>()).scenario.blocks.length).toBe(1);
  const after = await primary.get('/v1/leaderboards?category=mapper&period=all');
  expect((after.body as BoardBody).entries.map(row => row.account.nickname)).toEqual(['E2EPivar']);
  await openRoute({ device, screen }, '/leaderboards');
  await agent.act('Obnov žebříček stažením seznamu dolů.');
  await agent.assert('Žebříček po obnovení neobsahuje zablokovaného E2EKamos ani soukromého E2ECizi.');
  local.screenshot('social-private-blocked-board');
});

test('contest consent keeps diary privacy and vote moves instead of multiplying', { tags: ['critical', 'full'] }, async ({ app, screen, agent, device, local }) => {
  await local.reset('places_social');
  await signIn({ app, screen, device });
  await openRoute({ device, screen }, '/photo-contest');
  await agent.act('Přihlas do soutěže svou existující fotku E2E Fotka E2EPivar. Potvrď zveřejnění v soutěži. Nefotografuj a nevybírej novou fotku z galerie.');
  await expect.poll(async () => (await local.state<SocialState>()).scenario.entries.filter(row => row.account__nickname === 'E2EPivar').length).toBe(1);
  expect((await local.state<SocialState>()).scenario.photos.find(row => row.account__nickname === 'E2EPivar')?.visibility).toBe('private');
  const friend = await observer('second');
  const enteredFeed = await friend.get('/v1/friends/beer-photos/feed');
  expect(enteredFeed.status).toBe(200);
  expect(JSON.stringify(enteredFeed.body)).not.toContain('E2E Fotka E2EPivar');
  const voteFriend = screen.getByRole('button', 'Dát hlas fotce od @E2EKamos');
  await screen.scrollUntilVisible(voteFriend, { direction: 'down' });
  await voteFriend.tap();
  await expect.poll(async () => (await local.state<SocialState>()).scenario.votes).toEqual([{ voter__nickname: 'E2EPivar', entry__account__nickname: 'E2EKamos' }]);
  const voteOther = screen.getByRole('button', 'Dát hlas fotce od @E2ECizi');
  await screen.scrollUntilVisible(voteOther, { direction: 'up' });
  await voteOther.tap();
  await expect.poll(async () => (await local.state<SocialState>()).scenario.votes).toEqual([{ voter__nickname: 'E2EPivar', entry__account__nickname: 'E2ECizi' }]);
  await screen.getByRole('button', 'Vzít hlas fotce od @E2ECizi').tap();
  await expect.poll(async () => (await local.state<SocialState>()).scenario.votes).toEqual([]);
  await agent.act('Stáhni svou vlastní fotku ze soutěže a potvrď stažení.');
  await expect.poll(async () => (await local.state<SocialState>()).scenario.entries.filter(row => row.account__nickname === 'E2EPivar')).toEqual([]);
  expect((await local.state<SocialState>()).scenario.photos.find(row => row.account__nickname === 'E2EPivar')?.visibility).toBe('private');
  const feed = await friend.get('/v1/friends/beer-photos/feed');
  expect(feed.status).toBe(200);
  expect(JSON.stringify(feed.body)).not.toContain('E2E Fotka E2EPivar');
  await expect(screen.getByRole('button', 'Stáhnout ze soutěže')).not.toBeVisible();
  await expect(screen.getByRole('button', 'Vyfotit soutěžní fotku')).toBeVisible();
  local.screenshot('social-contest-withdrawn');
});
