import { expect } from 'e2e';
import { test } from '../../helpers/test';
import { signIn } from '../../helpers/navigation';
import { countMenuBeer, countOtherBeer, finishEvening, openCounter, openDiary, openLatestEvening, restartDiaryApp, type DiaryState } from './ui';

test('offline archived evening edits survive restart and reconcile exact stats', { tags: ['critical', 'full', 'diary'], timeout: 600_000 }, async ({ app, screen, agent, device, local }) => {
  await local.reset('diary');
  await app.clearState();
  const ui = { app, screen, agent, device };
  await signIn(ui);
  await openCounter(ui);
  await countMenuBeer(ui);
  await expect.poll(async () => (await local.state<DiaryState>()).scenario.drinks.length).toBe(1);
  const original = (await local.state<DiaryState>()).scenario.drinks[0];
  await countOtherBeer(ui, 'E2E Odebrat', 47);
  await expect.poll(async () => (await local.state<DiaryState>()).scenario.drinks.length).toBe(2);
  const removable = (await local.state<DiaryState>()).scenario.drinks.find(d => d.beer_name === 'E2E Odebrat')!;
  await local.offline();
  await countOtherBeer(ui, 'E2E Offline', 43);
  await finishEvening(ui);
  await restartDiaryApp(ui);
  await openLatestEvening(ui);
  await agent.assert('Detail ukončeného večera E2E U Testera ukazuje tři piva E2E Ležák, E2E Odebrat a E2E Offline, celkem 131 Kč.');
  await screen.getByTestId(`evening-edit-${original.client_id}`).tap();
  await screen.getByTestId('evening-edit-name-input').fill('E2E Opravený');
  await screen.getByTestId('evening-edit-save').tap();
  await screen.getByTestId(`evening-delete-${removable.client_id}`).tap();
  await screen.getByRole('button', 'Odebrat').tap();
  await restartDiaryApp(ui);
  await openLatestEvening(ui);
  await agent.assert('V detailu ukončeného večera právě dvě piva: E2E Opravený za 41 Kč a E2E Offline za 43 Kč, celkem 84 Kč. E2E Odebrat už v detailu není.');
  await local.online();
  await device.home();
  await app.open();
  await expect.poll(async () => (await local.state<DiaryState>()).scenario.drinks.map(d => d.beer_name)).toEqual(['E2E Opravený', 'E2E Offline']);
  const synced = (await local.state<DiaryState>()).scenario;
  expect(synced.drinks[0]).toMatchObject({ client_id: original.client_id, drank_at: original.drank_at, name: 'E2E U Testera', price_czk: 41, volume_ml: 500 });
  expect(synced.drinks[1]).toMatchObject({ beer_name: 'E2E Offline', name: 'E2E U Testera', price_czk: 43, volume_ml: 500 });
  expect(synced.drinks.map(d => d.client_id)).not.toContain(removable.client_id);
  expect(synced.visits).toHaveLength(1);
  expect(synced.visits[0].closed_at).not.toBeNull();
  expect(synced.stats).toEqual({ total_beers: 2, total_evenings: 1, distinct_pubs: 1, total_spent_czk: 84 });
  await restartDiaryApp(ui);
  await openDiary(ui);
  await screen.getByTestId('diary-stats-open').tap();
  await agent.assert('Statistiky za celou dobu ukazují 2 piva, 1 večer, 1 hospodu a 84 Kč.');
  local.screenshot('diary-offline-reconciled-stats');
  expect((await local.state<DiaryState>()).scenario.drinks).toEqual(synced.drinks);
});
