import { expect } from 'e2e';
import { test } from '../../helpers/test';
import { observer } from '../../helpers/backend';
import { openRoute, signIn, signInExisting } from '../../helpers/navigation';
import { copiedTourToken, createTour, openCreatedTour, openTourToken, restartDiaryApp, type DiaryState } from './ui';

test('private tour and counter progress persist offline through completion', { tags: ['critical', 'full', 'diary'], timeout: 600_000 }, async ({ app, screen, agent, device, local }) => {
  await local.reset('diary');
  await app.clearState();
  const ui = { app, screen, agent, device };
  await signIn(ui);
  await createTour(ui, 'E2E Soukromá tour');
  await local.offline();
  await screen.getByTestId('tour-save').tap();
  await restartDiaryApp(ui);
  await openCreatedTour(ui, 'E2E Soukromá tour');
  await agent.assert('Uložená soukromá tour obsahuje přesně dvě zastávky, nejdřív E2E U Testera a potom E2E Druhá hospoda.');
  await screen.getByRole('button', 'Vyrazit').tap();
  await screen.getByRole('button', 'Zapsat pivo na jedničce').tap();
  await agent.act('Zapiš právě jedno pivo E2E Tour za 41 Kč, objem 0,5 l, v předané hospodě E2E U Testera. Nevyměňuj hospodu a nepřidávej další pivo.').catch(error => {
    local.screenshot('diary-tour-beer-form-failed');
    throw error;
  });
  await restartDiaryApp(ui);
  await openCreatedTour(ui, 'E2E Soukromá tour');
  await agent.assert('V běžícím průchodu tour je E2E U Testera navštívená s jedním pivem. E2E Druhá hospoda je další nevyřízená zastávka.');
  await agent.act('V běžící tour otevři druhou zastávku E2E Druhá hospoda a zvol Přeskočit zastávku. Potom ukonči tour a potvrď ukončení průchodu. Neoznačuj druhou hospodu jako navštívenou.');
  await restartDiaryApp(ui);
  await openCreatedTour(ui, 'E2E Soukromá tour');
  await agent.act('Otevři dokončený historický průchod této tour. Nezačínej nový průchod.');
  await agent.assert('Dokončený průchod má první zastávku navštívenou s jedním pivem a druhou přeskočenou. Průchod už neběží.');
  await local.online();
  await device.home();
  await app.open();
  await expect.poll(async () => (await local.state<DiaryState>()).scenario.drinks.length).toBe(1);
  const state = (await local.state<DiaryState>()).scenario;
  expect(state.drinks[0]).toMatchObject({ beer_name: 'E2E Tour', price_czk: 41, volume_ml: 500, name: 'E2E U Testera' });
  expect(state.plans).toEqual([]);
  expect(state.shares).toEqual([]);
  expect(state.publications).toEqual([]);
  local.screenshot('diary-private-tour-history');
});

test('shared tour imports once and revoked private and public links close', { tags: ['critical', 'full', 'diary'], timeout: 900_000 }, async ({ app, screen, agent, device, local }) => {
  await local.reset('diary');
  await app.clearState();
  const ui = { app, screen, agent, device };
  await signIn(ui);
  await createTour(ui, 'E2E Sdílená tour');
  await screen.getByTestId('tour-save').tap();
  await agent.act('V této tour otevři nabídku dalších možností a Odkaz na tour. Vytvoř soukromý odkaz a zkopíruj ho tlačítkem Kopírovat odkaz. Odkaz nikam nevkládej, neotvírej systémové sdílení.').catch(async error => {
    if (await screen.getByRole('button', 'Vytvořit odkaz').isVisible()) local.screenshot('diary-tour-link-create-failed');
    throw error;
  });
  const privateToken = copiedTourToken();
  await expect.poll(async () => (await local.state<DiaryState>()).scenario.shares.length).toBe(1);
  const privatePlan = (await local.state<DiaryState>()).scenario.plans[0];
  expect(privatePlan.stops.map(stop => stop.name)).toEqual(['E2E U Testera', 'E2E Druhá hospoda']);
  const primary = await observer();
  expect((await primary.get(`/v1/tour-shares/${privateToken}`)).status).toBe(200);
  await agent.act('Vrať se z náhledu sdíleného plánu k vlastní tour. V nabídce této tour zvol Zveřejnit pro všechny. Zatím nepotvrzuj samotné zveřejnění.');
  await expect(screen.getByTestId('tour-publish')).toBeVisible();
  await screen.getByTestId('tour-publish').tap();
  await expect.poll(async () => (await local.state<DiaryState>()).scenario.publications.map(p => p.status)).toEqual(['active']);
  const publication = (await local.state<DiaryState>()).scenario.publications[0];
  expect(publication.stopNames).toEqual(['E2E U Testera', 'E2E Druhá hospoda']);
  expect(publication.snapshotKeys).not.toContain('scheduled_date');
  expect(publication.snapshotKeys).not.toContain('scheduled_time');
  await agent.act('V nabídce této vlastní tour zvol Sdílet veřejný odkaz a zkopíruj veřejný odkaz, pokud appka otevře sdílení. Odkaz nikam nevkládej.');
  const publicToken = copiedTourToken();
  expect(publicToken === privateToken).toBe(false);
  expect((await primary.get(`/v1/tour-shares/${publicToken}`)).status).toBe(200);

  await openRoute(ui, '/account');
  await agent.act('Odhlas přihlášený účet E2E Pivař tlačítkem Odhlásit se a potvrď odhlášení. Účet nemaž.');
  await signInExisting(ui, 'secondEmail');
  await openTourToken(ui, privateToken);
  await agent.act('Ulož sdílenou tour E2E Sdílená tour do svých tour. Nezačínej průchod a nic nezveřejňuj.');
  await restartDiaryApp(ui);
  await openCreatedTour(ui, 'E2E Sdílená tour');
  await agent.assert('Detail tour E2E Sdílená tour obsahuje právě dvě zastávky: nejdřív E2E U Testera a potom E2E Druhá hospoda.');
  await openTourToken(ui, privateToken);
  await agent.act('Otevři již uloženou tour E2E Sdílená tour. Nevytvářej druhou kopii.');
  await openRoute(ui, '/tours');
  await agent.assert('Moje tour obsahují právě jednu kopii E2E Sdílená tour.');
  local.screenshot('diary-imported-tour-once');

  await openRoute(ui, '/account');
  await agent.act('Odhlas účet E2E Příjemce a potvrď odhlášení. Účet nemaž.');
  await signInExisting(ui);
  await openRoute(ui, '/tours');
  await agent.act('Obnov moje publikované tour ze serveru. Pokud potvrzení říká že byly obnovené, zavři ho a otevři E2E Sdílená tour.');
  await agent.act('V nabídce této vlastní tour stáhni její veřejnou verzi a potvrď stažení. Potom v Odkaz na tour zruš soukromý odkaz a potvrď zrušení. Uložený plán nemaž.');
  await expect.poll(async () => (await local.state<DiaryState>()).scenario.publications.map(p => p.status)).toEqual(['unpublished']);
  expect((await local.state<DiaryState>()).scenario.shares[0].revoked_at).not.toBeNull();
  expect((await primary.get(`/v1/tour-shares/${privateToken}`)).status).toBe(404);
  expect((await primary.get(`/v1/tour-shares/${publicToken}`)).status).toBe(404);
  await restartDiaryApp(ui);
  await openCreatedTour(ui, 'E2E Sdílená tour');
  await agent.assert('Detail tour E2E Sdílená tour obsahuje právě dvě zastávky: nejdřív E2E U Testera a potom E2E Druhá hospoda.');
  await screen.getByRole('button', 'Možnosti tour').tap();
  await expect(screen.getByRole('button', 'Zveřejnit pro všechny')).toBeVisible();
  await expect(screen.getByRole('button', 'Sdílet veřejný odkaz')).not.toBeVisible();
  await expect(screen.getByRole('button', 'Stáhnout z veřejných')).not.toBeVisible();
  await screen.getByRole('button', 'Odkaz na tour').tap();
  await expect(screen.getByRole('button', 'Vytvořit odkaz')).toBeVisible();
  await expect(screen.getByRole('button', 'Zrušit odkaz')).not.toBeVisible();
  local.screenshot('diary-tour-links-withdrawn');
  const final = (await local.state<DiaryState>()).scenario;
  expect(final.plans).toHaveLength(1);
  expect(final.plans[0].id).toBe(privatePlan.id);
  expect(final.drinks).toEqual([]);
});
