name: Uprate iOS Build and Submit

jobs:
  build:
    name: Build iOS production
    type: build
    params:
      platform: ios
      profile: production

  submit:
    name: Submit iOS production
    type: submit
    needs: [build]
    params:
      build_id: ${{ needs.build.outputs.build_id }}
      profile: production
